### ISSUE TITLE
Unicode/decode error

### ISSUE THREAD

**Issue by JimMcNulty** [Tautulli/Tautulli#1042]
**Version:**  I'm not really sure, because it's not working. Changelog says 1.4.18

**Operating system:** Windows 10

**Python version:** 2.7.13

**What you did?** I've never had an issue and I haven't make any changes to the computer. No new software. I've only changed the ip address.

**What happened?** Plexpy is not working.

**What are your (relevant) settings?** I installed it several months ago and it was working fine. No special settings. I followed the steps to install it as an interactive daemon.

**Link to logs:** 
`2017-05-26 10:34:20 - INFO    :: MainThread : Checking to see if the database has all tables....

2017-05-26 10:34:20 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\PlexPy

2017-05-26 10:34:22 - DEBUG   :: MainThread : Git output: ed2d34e97945525a5f83f6b9edc3350df54057b8

2017-05-26 10:34:23 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\PlexPy

2017-05-26 10:34:23 - DEBUG   :: MainThread : Git output: master
2017-05-26 10:34:23 - INFO    :: MainThread : Retrieving latest version information from GitHub
2017-05-26 10:34:23 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master

2017-05-26 10:34:24 - DEBUG   :: MainThread : Latest version is ed2d34e97945525a5f83f6b9edc3350df54057b8

2017-05-26 10:34:24 - INFO    :: MainThread : PlexPy is up to date
2017-05-26 10:34:24 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2017-05-26 10:34:24 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-05-26 10:34:24 - DEBUG   :: MainThread : PlexPy PlexTV :: Plex Pass subscription not found.
2017-05-26 10:34:24 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-05-26 10:34:24 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-05-26 10:34:24 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2017-05-26 10:34:24 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2017-05-26 10:34:39 - WARNING :: MainThread : Failed to access uri endpoint /:/prefs with error timed out

2017-05-26 10:34:39 - WARNING :: MainThread : PlexPy Pmsconnect :: Unable to parse XML for get_local_server_name: 'NoneType' object has no attribute 'getElementsByTagName'.

2017-05-26 10:34:40 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\PlexPy\PlexPy.py", line 260, in <module>
    main()
  File "C:\PlexPy\PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "C:\PlexPy\plexpy\__init__.py", line 190, in initialize
    pmsconnect.get_server_friendly_name()
  File "C:\PlexPy\plexpy\pmsconnect.py", line 37, in get_server_friendly_name
    servers_info = PmsConnect().get_servers_info()
  File "C:\PlexPy\plexpy\pmsconnect.py", line 1608, in get_servers_info
    recent = self.get_server_list(output_format='xml')
  File "C:\PlexPy\plexpy\pmsconnect.py", line 272, in get_server_list
    output_format=output_format)
  File "C:\PlexPy\plexpy\http_handler.py", line 89, in make_request
    logger.warn(u"Failed to access uri endpoint %s with error %s" % (uri, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 47: ordinal not in range(128)`

**Comment by JimMcNulty** [comment]
I managed to get it working. I had to edit config file and changed the old ip address for the new one.
