### ISSUE TITLE
Unable to start after reboot.

### ISSUE THREAD

**Issue by bsheairs928** [Tautulli/Tautulli#1066]
Currently have it installed as a Daemon on Mac OSX.  Had to restart after updates, and noticed that it was not running.  Tried to start in manually and received the following message from the Terminal:
2017-07-08 09:03:54 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "plexpy.py", line 260, in <module>
    main()
  File "plexpy.py", line 186, in main
    plexpy.initialize(config_file)
  File "/Applications/PlexPy/plexpy/__init__.py", line 96, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/PlexPy/plexpy/config.py", line 639, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "128".

Traceback (most recent call last):
  File "plexpy.py", line 260, in <module>
    main()
  File "plexpy.py", line 186, in main
    plexpy.initialize(config_file)
  File "/Applications/PlexPy/plexpy/__init__.py", line 96, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/PlexPy/plexpy/config.py", line 639, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
configobj.ParseError: Invalid line at line "128".

Attempted to pull to ensure code was up-to-date but received the same error.

**Version:**
1.4.21
**Branch:**
Main
**Commit hash:**

**Operating system:**
OSX 10.11.6
**Python version:**

**What you did?**

**What happened?**

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by Hellowlol** [comment]
your config file is fucked up. use the backup
