### ISSUE TITLE
Issue with NGINX

### ISSUE THREAD

**Issue by Dukko** [Tautulli/Tautulli#1073]
I can't start PlexPy anymore after a reboot.

The error log says:
`2017-07-15 11:21:35 - INFO    :: MainThread : Checking to see if the database has all tables....
2017-07-15 11:21:35 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:21:35 - DEBUG   :: MainThread : Git output: af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:21:35 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:21:35 - DEBUG   :: MainThread : Git output: master
2017-07-15 11:21:35 - INFO    :: MainThread : Retrieving latest version information from GitHub
2017-07-15 11:21:35 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-07-15 11:21:36 - DEBUG   :: MainThread : Latest version is af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:21:36 - INFO    :: MainThread : PlexPy is up to date
2017-07-15 11:21:36 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2017-07-15 11:21:36 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:37 - DEBUG   :: MainThread : PlexPy PlexTV :: Plex Pass subscription not found.
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Check for Plex updates
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh users list
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Backup PlexPy config
2017-07-15 11:21:39 - DEBUG   :: MainThread : PlexPy Monitor :: Session 194 has stopped.
2017-07-15 11:21:39 - DEBUG   :: MainThread : PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'
2017-07-15 11:21:39 - WARNING :: MainThread : Websocket :: Unable to open connection.
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Check for active sessions
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy WebStart :: Web server authentication is enabled, username is 'Dukko'
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://dukkokun.ddns.net:8181/plexpy/
2017-07-15 11:21:41 - ERROR   :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "C:\ProgramData\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\ProgramData\PlexPy\lib/cherrypy\process\servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "C:\ProgramData\PlexPy\lib/cherrypy\wsgiserver\wsgiserver2.py", line 1935, in start
    raise socket.error(msg)
error: No socket could be created -- (('174.***.***.***', 8181): [Errno 10049] The requested address is not valid in its context)

2017-07-15 11:38:13 - INFO    :: MainThread : Checking to see if the database has all tables....
2017-07-15 11:38:13 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:38:14 - DEBUG   :: MainThread : Git output: af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:38:14 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:38:14 - DEBUG   :: MainThread : Git output: master
2017-07-15 11:38:14 - INFO    :: MainThread : Retrieving latest version information from GitHub
2017-07-15 11:38:14 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-07-15 11:38:15 - DEBUG   :: MainThread : Latest version is af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:38:15 - INFO    :: MainThread : PlexPy is up to date
2017-07-15 11:38:15 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2017-07-15 11:38:15 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:16 - DEBUG   :: MainThread : PlexPy PlexTV :: Plex Pass subscription not found.
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Check for Plex updates
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh users list
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Backup PlexPy config
2017-07-15 11:38:18 - DEBUG   :: MainThread : PlexPy Monitor :: Session 194 has stopped.
2017-07-15 11:38:18 - DEBUG   :: MainThread : PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'
2017-07-15 11:38:18 - WARNING :: MainThread : Websocket :: Unable to open connection.
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Check for active sessions
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy WebStart :: Web server authentication is enabled, username is 'Dukko'
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://dukkokun.ddns.net:8181/plexpy/
2017-07-15 11:38:20 - ERROR   :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "C:\ProgramData\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\ProgramData\PlexPy\lib/cherrypy\process\servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "C:\ProgramData\PlexPy\lib/cherrypy\wsgiserver\wsgiserver2.py", line 1935, in start
    raise socket.error(msg)
error: No socket could be created -- (('174.***.***.***', 8181): [Errno 10049] The requested address is not valid in its context)

2017-07-15 11:39:08 - INFO    :: MainThread : Checking to see if the database has all tables....
2017-07-15 11:39:08 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:39:08 - DEBUG   :: MainThread : Git output: af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:39:08 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:39:08 - DEBUG   :: MainThread : Git output: master
2017-07-15 11:39:08 - INFO    :: MainThread : Retrieving latest version information from GitHub
2017-07-15 11:39:08 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-07-15 11:39:09 - DEBUG   :: MainThread : Latest version is af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:39:09 - INFO    :: MainThread : PlexPy is up to date
2017-07-15 11:39:09 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2017-07-15 11:39:09 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:10 - DEBUG   :: MainThread : PlexPy PlexTV :: Plex Pass subscription not found.
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2017-07-15 11:39:11 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
2017-07-15 11:39:11 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Check for Plex updates
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh users list
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Backup PlexPy config
2017-07-15 11:39:12 - DEBUG   :: MainThread : PlexPy Monitor :: Session 194 has stopped.
2017-07-15 11:39:12 - DEBUG   :: MainThread : PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'
2017-07-15 11:39:12 - WARNING :: MainThread : Websocket :: Unable to open connection.
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Check for active sessions
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy WebStart :: Web server authentication is enabled, username is 'Dukko'
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://dukkokun.ddns.net:8181/plexpy/
2017-07-15 11:39:13 - ERROR   :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "C:\ProgramData\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\ProgramData\PlexPy\lib/cherrypy\process\servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "C:\ProgramData\PlexPy\lib/cherrypy\wsgiserver\wsgiserver2.py", line 1935, in start
    raise socket.error(msg)
error: No socket could be created -- (('174.***.***.***', 8181): [Errno 10049] The requested address is not valid in its context)

`

I'm trying to reroute it through NGINX and it worked before the reboot. Any ideas?

**Comment by JonnyWong16** [comment]
Don't change the http host. https://i.imgur.com/zDPsQfJ.png

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#general-q4

**Comment by Dukko** [comment]
I deleted the two lines but it stills shows the same error.

> 2017-07-15 11:21:35 - INFO    :: MainThread : Checking to see if the database has all tables....
2017-07-15 11:21:35 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:21:35 - DEBUG   :: MainThread : Git output: af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:21:35 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:21:35 - DEBUG   :: MainThread : Git output: master
2017-07-15 11:21:35 - INFO    :: MainThread : Retrieving latest version information from GitHub
2017-07-15 11:21:35 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-07-15 11:21:36 - DEBUG   :: MainThread : Latest version is af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:21:36 - INFO    :: MainThread : PlexPy is up to date
2017-07-15 11:21:36 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2017-07-15 11:21:36 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:37 - DEBUG   :: MainThread : PlexPy PlexTV :: Plex Pass subscription not found.
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2017-07-15 11:21:37 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Check for Plex updates
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh users list
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Backup PlexPy config
2017-07-15 11:21:39 - DEBUG   :: MainThread : PlexPy Monitor :: Session 194 has stopped.
2017-07-15 11:21:39 - DEBUG   :: MainThread : PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'
2017-07-15 11:21:39 - WARNING :: MainThread : Websocket :: Unable to open connection.
2017-07-15 11:21:39 - INFO    :: MainThread : Scheduled background task: Check for active sessions
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy WebStart :: Web server authentication is enabled, username is 'Dukko'
2017-07-15 11:21:39 - INFO    :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://dukkokun.ddns.net:8181/plexpy/
2017-07-15 11:21:41 - ERROR   :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "C:\ProgramData\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\ProgramData\PlexPy\lib/cherrypy\process\servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "C:\ProgramData\PlexPy\lib/cherrypy\wsgiserver\wsgiserver2.py", line 1935, in start
    raise socket.error(msg)
error: No socket could be created -- (('174.***.***.***', 8181): [Errno 10049] The requested address is not valid in its context)

2017-07-15 11:38:13 - INFO    :: MainThread : Checking to see if the database has all tables....
2017-07-15 11:38:13 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:38:14 - DEBUG   :: MainThread : Git output: af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:38:14 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:38:14 - DEBUG   :: MainThread : Git output: master
2017-07-15 11:38:14 - INFO    :: MainThread : Retrieving latest version information from GitHub
2017-07-15 11:38:14 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-07-15 11:38:15 - DEBUG   :: MainThread : Latest version is af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:38:15 - INFO    :: MainThread : PlexPy is up to date
2017-07-15 11:38:15 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2017-07-15 11:38:15 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:16 - DEBUG   :: MainThread : PlexPy PlexTV :: Plex Pass subscription not found.
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2017-07-15 11:38:16 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Check for Plex updates
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh users list
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Backup PlexPy config
2017-07-15 11:38:18 - DEBUG   :: MainThread : PlexPy Monitor :: Session 194 has stopped.
2017-07-15 11:38:18 - DEBUG   :: MainThread : PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'
2017-07-15 11:38:18 - WARNING :: MainThread : Websocket :: Unable to open connection.
2017-07-15 11:38:18 - INFO    :: MainThread : Scheduled background task: Check for active sessions
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy WebStart :: Web server authentication is enabled, username is 'Dukko'
2017-07-15 11:38:18 - INFO    :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://dukkokun.ddns.net:8181/plexpy/
2017-07-15 11:38:20 - ERROR   :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "C:\ProgramData\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\ProgramData\PlexPy\lib/cherrypy\process\servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "C:\ProgramData\PlexPy\lib/cherrypy\wsgiserver\wsgiserver2.py", line 1935, in start
    raise socket.error(msg)
error: No socket could be created -- (('174.***.***.***', 8181): [Errno 10049] The requested address is not valid in its context)

2017-07-15 11:39:08 - INFO    :: MainThread : Checking to see if the database has all tables....
2017-07-15 11:39:08 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:39:08 - DEBUG   :: MainThread : Git output: af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:39:08 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\ProgramData\PlexPy
2017-07-15 11:39:08 - DEBUG   :: MainThread : Git output: master
2017-07-15 11:39:08 - INFO    :: MainThread : Retrieving latest version information from GitHub
2017-07-15 11:39:08 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-07-15 11:39:09 - DEBUG   :: MainThread : Latest version is af77e5130761850fd79038fef9b623269c02f04f
2017-07-15 11:39:09 - INFO    :: MainThread : PlexPy is up to date
2017-07-15 11:39:09 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2017-07-15 11:39:09 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:10 - DEBUG   :: MainThread : PlexPy PlexTV :: Plex Pass subscription not found.
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2017-07-15 11:39:10 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2017-07-15 11:39:11 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
2017-07-15 11:39:11 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Check GitHub for updates
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh Plex server URLs
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh Plex server name
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Check for Plex updates
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh users list
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Refresh libraries list
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Backup PlexPy database
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Backup PlexPy config
2017-07-15 11:39:12 - DEBUG   :: MainThread : PlexPy Monitor :: Session 194 has stopped.
2017-07-15 11:39:12 - DEBUG   :: MainThread : PlexPy ActivityProcessor :: ratingKey None not logged. Does not meet logging criteria. Media type is 'None'
2017-07-15 11:39:12 - WARNING :: MainThread : Websocket :: Unable to open connection.
2017-07-15 11:39:12 - INFO    :: MainThread : Scheduled background task: Check for active sessions
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy WebStart :: Web server authentication is enabled, username is 'Dukko'
2017-07-15 11:39:12 - INFO    :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://dukkokun.ddns.net:8181/plexpy/
2017-07-15 11:39:13 - ERROR   :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "C:\ProgramData\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\ProgramData\PlexPy\lib/cherrypy\process\servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "C:\ProgramData\PlexPy\lib/cherrypy\wsgiserver\wsgiserver2.py", line 1935, in start
    raise socket.error(msg)
error: No socket could be created -- (('174.***.***.***', 8181): [Errno 10049] The requested address is not valid in its context)

**Comment by JonnyWong16** [comment]
Make sure the python process is not running. It doesn't look like you changed the config file.

**Comment by Dukko** [comment]
Uh, seems like rebooting AGAIN made it work. Thanks and sorry for wasting your time 👍
