### ISSUE TITLE
Facebook updates and prowl not working since latest update

### ISSUE THREAD

**Issue by kevmasonk1** [Tautulli/Tautulli#1094]
Hi

Since latest update facebook updates now no longer work (Automated when something added to the library) Only test notification works.
Also Prowl doesn't work even on test, instead just get an error message advising 500 internal server error.

Tried full reinstall but same issue.

No error in logs at all it appears to have sent, please advise

Extra detail

 Version -  VERSION 1.4.22
 Branch -  Master
 Commit hash - ec685407bbd4924b7c94c2dab2f1754089e77322
 Operating system - Linux 4.4.0-69-generic
 Python version - 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
 What you did? - Nothing just applied latest update
 What happened? - As detail notifications stopped working
 What you expected? - N/A
 How can we reproduce your issue? - Issue still present
 What are your (relevant) settings? - Unsure advise if any extra detail needed

**Comment by JonnyWong16** [comment]
Post your logs.

**Comment by kevmasonk1** [comment]
2017-08-21 18:49:24 - INFO    :: CP Server Thread-5 : Cleared the plexpy.log file.
2017-08-21 18:49:41 - INFO    :: CP Server Thread-8 : PlexPy Config :: Writing configuration to file
2017-08-21 18:49:41 - DEBUG   :: CP Server Thread-8 : Sending test Prowl notification.
2017-08-21 18:50:09 - INFO    :: CP Server Thread-3 : PlexPy Config :: Writing configuration to file
2017-08-21 18:50:09 - DEBUG   :: CP Server Thread-3 : Sending test Facebook notification.
2017-08-21 18:50:11 - INFO    :: CP Server Thread-3 : PlexPy Notifiers :: Facebook notification sent.
2017-08-21 18:55:08 - DEBUG   :: Thread-25 : PlexPy Monitor :: Session 110 has started with ratingKey 16690.
2017-08-21 18:56:09 - DEBUG   :: Thread-26 : PlexPy Monitor :: Session 110 has stopped.
2017-08-21 18:56:09 - DEBUG   :: Thread-26 : PlexPy ActivityProcessor :: ratingKey 16690 not logged. Does not meet logging criteria. Media type is 'clip'
2017-08-21 18:56:09 - DEBUG   :: Thread-26 : PlexPy Monitor :: Removing sessionKey 110 ratingKey 16690 from session queue
2017-08-21 18:56:09 - DEBUG   :: Thread-26 : PlexPy Monitor :: Session 110 has started with ratingKey 27431.
2017-08-21 18:56:09 - ERROR   :: Thread-29 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 68, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2017-08-21 18:56:09 - ERROR   :: Thread-30 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 216, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2017-08-21 18:57:08 - DEBUG   :: Thread-22 : PlexPy Monitor :: Session 110 has stopped.
2017-08-21 18:57:08 - DEBUG   :: Thread-22 : PlexPy ActivityProcessor :: Play duration for ratingKey 27431 is 59 secs which is less than 120 seconds, so we're not logging it.
2017-08-21 18:57:08 - DEBUG   :: Thread-22 : PlexPy Monitor :: Removing sessionKey 110 ratingKey 27431 from session queue
2017-08-21 19:26:08 - DEBUG   :: Thread-26 : PlexPy Monitor :: Session 111 has started with ratingKey 24536.
2017-08-21 19:26:09 - ERROR   :: Thread-31 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 68, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2017-08-21 19:26:09 - ERROR   :: Thread-32 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 216, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2017-08-21 19:54:08 - DEBUG   :: Thread-20 : PlexPy Monitor :: Session 112 has started with ratingKey 22028.
2017-08-21 19:54:09 - ERROR   :: Thread-34 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 216, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2017-08-21 19:54:09 - ERROR   :: Thread-33 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 68, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2017-08-21 20:00:08 - DEBUG   :: Thread-18 : PlexPy Monitor :: Session 112 has been paused.
2017-08-21 20:05:08 - DEBUG   :: Thread-18 : PlexPy Monitor :: Session 112 has stopped.
2017-08-21 20:05:08 - DEBUG   :: Thread-18 : PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 22028
2017-08-21 20:05:08 - DEBUG   :: Thread-18 : PlexPy Monitor :: Removing sessionKey 112 ratingKey 22028 from session queue
2017-08-21 20:07:08 - DEBUG   :: Thread-21 : PlexPy Monitor :: Session 113 has started with ratingKey 28810.
2017-08-21 20:07:09 - ERROR   :: Thread-36 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 216, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2017-08-21 20:07:09 - ERROR   :: Thread-35 : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 68, in notify
    metadata=metadata)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification
    return prowl.notify(message=body, event=subject)
  File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify
    body=urlencode(data))
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

**Comment by JonnyWong16** [comment]
That's a lot of SSL errors for Prowl. You're going to have to look that up yourself. I have no experience with Prowl.

I'm going to need to see the logs for Facebook notifications when it fails. Not when you're testing.

**Comment by kevmasonk1** [comment]
Is it possible to have a rolled back version?
With the facebook notifications there are no logs at all, When an item is added to the server and picked up in the library nothing happens.
When I click the test option it posts successfully

Any help greatly appreciated







  |   |  
-- | -- | --
2017-08-22 20:56:27 | ERROR | Uncaught exception: Traceback (most recent call last):    File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run         old_run(*args, **kwargs)     File "/usr/lib/python2.7/threading.py", line 763, in run         self.__target(*self.__args, **self.__kwargs)     File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 68, in notify         metadata=metadata)     File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification         return prowl.notify(message=body, event=subject)     File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify         body=urlencode(data))     File "/usr/lib/python2.7/httplib.py", line 1017, in request         self._send_request(method, url, body, headers)     File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request         self.endheaders(body)     File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders         self._send_output(message_body)     File "/usr/lib/python2.7/httplib.py", line 864, in _send_output         self.send(msg)     File "/usr/lib/python2.7/httplib.py", line 826, in send         self.connect()     File "/usr/lib/python2.7/httplib.py", line 1220, in connect         self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)     File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket         ciphers=ciphers)     File "/usr/lib/python2.7/ssl.py", line 243, in __init__         self.do_handshake()     File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake         self._sslobj.do_handshake() SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2017-08-22 20:36:27 | ERROR | Uncaught exception: Traceback (most recent call last):    File "/home/hd1/masonk1/apps/plexpy/plexpy/logger.py", line 270, in new_run         old_run(*args, **kwargs)     File "/usr/lib/python2.7/threading.py", line 763, in run         self.__target(*self.__args, **self.__kwargs)     File "/home/hd1/masonk1/apps/plexpy/plexpy/notification_handler.py", line 391, in notify_timeline         metadata=metadata)     File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 560, in send_notification         return prowl.notify(message=body, event=subject)     File "/home/hd1/masonk1/apps/plexpy/plexpy/notifiers.py", line 821, in notify         body=urlencode(data))     File "/usr/lib/python2.7/httplib.py", line 1017, in request         self._send_request(method, url, body, headers)     File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request         self.endheaders(body)

**Comment by JonnyWong16** [comment]
Make sure notifications are enabled (in three locations).

https://github.com/JonnyWong16/plexpy/wiki/Frequently-Asked-Questions-(FAQ)#q-i-cant-get-notifications-working-is-there-a-magic-trick

**Comment by kevmasonk1** [comment]
Yes already enabled in all three locations.
So it appears that the prowl notification failure blocks the facebook update. I have removed the prowl notification and cleared logs and restarted and facebook works successfully. Whne adding prowl back on it fails

**Comment by JonnyWong16** [comment]
So problem solved?

The Prowl SSL issue isn't with PlexPy. It's an issue on your system. Maybe try updating your version of Python,

**Comment by kevmasonk1** [comment]
Yes agreed its not with Plexpy, any advise on what I should update? or what version of Python will work?
