### ISSUE TITLE
plexwatch import error

### ISSUE THREAD

**Issue by bewser** [Tautulli/Tautulli#1099]
**Version:** 
1.4.22
**Branch:**
master
**Commit hash:**
ec685407bbd4924b7c94c2dab2f1754089e77322
**Operating system:**
Windows 10
**Python version:**
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
**What you did?**
Import database file from PlexWatch
**What happened?**
2017-08-27 15:11:16 - ERROR   :: Thread-25 : Uncaught exception: Traceback (most recent call last):
  File "C:\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\PlexPy\plexpy\plexwatch_import.py", line 419, in import_from_plexwatch
    import_ignore_interval=import_ignore_interval)
  File "C:\PlexPy\plexpy\activity_processor.py", line 296, in write_session_history
    metadata['duration'], metadata['width'], metadata['height'], metadata['container'],
KeyError: 'width'
**What you expected?**
A successful import of the PlexWatch db.
**How can we reproduce your issue?**
I can provide link to db, just let me know.

**What are your (relevant) settings?**

**Link to logs:**
https://gist.github.com/bewser/a1b22f5ae7be0b055f6f2a03d136d1ee#file-plexply-log

**Comment by veenarm** [comment]
I'm having the same error attempting to import PlexWatch.db

New installation of PlexPy - attempted different ignore intervals, different table grouping. Moving the db somewhere else. 

> Windows 10 > PlexPy 1.4.22 Master, ec68540***, Python 2.7.10

> Uncaught exception: Traceback (most recent call last):
    File "/opt/plexpy/plexpy/logger.py", line 270, in new_run 
        old_run(*args, **kwargs) 
    File "/usr/lib/python2.7/threading.py", line 763, in run 
        self.__target(*self.__args, **self.__kwargs) 
    File "/opt/plexpy/plexpy/plexwatch_import.py", line 419, in import_from_plexwatch 
        import_ignore_interval=import_ignore_interval) 
    File "/opt/plexpy/plexpy/activity_processor.py", line 296, in write_session_history 
        metadata['duration'], metadata['width'], metadata['height'], metadata['container'], 
KeyError: 'width' 

If you need my DB I can provide.

**Comment by daeks** [comment]
I have the same issue with latest version of plexpy. Any ETA when this issue is fixed?

**Comment by JonnyWong16** [comment]
No ETA. But you don't have to import it now. Just keep the database file and import it later when it is fixed.

**Comment by JonnyWong16** [comment]
Fixed in v1.4.23.
