### ISSUE TITLE
PlexPy won't start on Mac OS X after update from 10.13 to 10.13.1

### ISSUE THREAD

**Issue by bryannorton** [Tautulli/Tautulli#1138]
**Version:**
1.4.25

**Branch:**
Not sure how to answer this.  It's whatever Branch/Commit is downloaded from the main page when you click Download.

**Commit hash:**

**Operating system:**
Mac OS X 10.13.1

**Python version:**
2.7.10

**What you did?**
Attempted to start PlexPy after I noticed it was down.

**What happened?**
The last entry in the log is PlexPy shutting down on 10/31.  I just noticed it wasn't running today.  The only thing that has changed in the past two days is the update of my Mac from 10.13 to 10.13.1.  I downloaded the latest version from Github and overwrote all the files in my PlexPy directory, but still received the same error when I attempted to start it.  The error received is:

Bryans-iMac:PlexPy bryannorton$ python PlexPy.py 
2017-11-02 08:50:03 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "PlexPy.py", line 266, in <module>
    main()
  File "PlexPy.py", line 192, in main
    plexpy.initialize(config_file)
  File "/Applications/PlexPy/plexpy/__init__.py", line 97, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/PlexPy/plexpy/config.py", line 640, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "298".

Traceback (most recent call last):
  File "PlexPy.py", line 266, in <module>
    main()
  File "PlexPy.py", line 192, in main
    plexpy.initialize(config_file)
  File "/Applications/PlexPy/plexpy/__init__.py", line 97, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/PlexPy/plexpy/config.py", line 640, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
configobj.ParseError: Invalid line at line "298".

**What you expected?**
PlexPy to run

**How can we reproduce your issue?**

I don't know if the update to 10.13.1 caused the problem, but if you have a Mac running 10.13.1, attempt to start PlexPy and see what happens.

**What are your (relevant) settings?**

**Link to logs:**
https://www.dropbox.com/s/71j5y1u8mgekuwt/plexpy.log?dl=0

**Comment by JonnyWong16** [comment]
Your config file got messed up. Restore a backup from the backups folder or delete it.

**Comment by bryannorton** [comment]
Thanks!  Deleting the config.ini file fixed the issue.
