### ISSUE TITLE
Cant run PlexPy for the first time

### ISSUE THREAD

**Issue by idonava** [Tautulli/Tautulli#1155]
Hello,
For the first time i tried to install and use PlexPy, But unfortunately i'm not success.
My system:
1. Windows 10 pro. 
2. python-2.7.14 (Fresh install).
3. Git-2.15.0-64-bit (Fresh install).
4. plexpy-v1.4.25 (Fresh install).

After install all the softwares i mention above, I install PlexPy into C:\Program Files\PlexPy (With the install tutorial, Method 2).
When i tried to double click PlexPy.py, The windows closed immediately.
After that i tried running the py file manually  from cmd, By the command: 
`C:\Python27\python.exe "C:\Program Files\PlexPy\PlexPy.py"`
And got:
```
C:\Users\idona>C:\Python27\python.exe "C:\Program Files\PlexPy\PlexPy.py"
Unable to create the log directory. Logging to screen only.
Traceback (most recent call last):
  File "C:\Program Files\PlexPy\PlexPy.py", line 266, in <module>
    main()\n
  File "C:\Program Files\PlexPy\PlexPy.py", line 192, in main
    plexpy.initialize(config_file)
  File "C:\Program Files\PlexPy\plexpy\__init__.py", line 130, in initialize
    verbose=VERBOSE)
  File "C:\Program Files\PlexPy\plexpy\logger.py", line 205, in initLogger
    file_handler = handlers.RotatingFileHandler(filename, maxBytes=MAX_SIZE, backupCount=MAX_FILES)
  File "C:\Python27\lib\logging\handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: 'C:\\Users\\idona\\None\\plexpy.log'
```

What did i do wrong and how can i fix the problem ?

** I searched over the FAQ/Issues/Google but found nothing like mine problem.

Thanks !!!!

**Comment by JonnyWong16** [comment]
Don't put it in Program Files. PlexPy doesn't have permissions to create files/folders there.

**Comment by idonava** [comment]
Thanks, I just cut the PlexPy folder into C: and it works!
