### ISSUE TITLE
Error by Script Notification on Stop playing an TV-Show

### ISSUE THREAD

**Issue by Kriss321** [Tautulli/Tautulli#1159]
**Version:** latest Version

**Branch:** V2

**Commit hash:** ffb38ef

**Operating system:** Debian 9.2

**Python version:** Python 2.7.13

**What you did?** Script Notification on Stop playing an TV-Show

**What happened?** I get an Error

**What you expected?** Executing Script

**Link to logs:**
2017-12-02 15:06:10 - ERROR :: Thread-1 : PlexPy NotificationHandler :: Notification thread exception: 'bool' object is not callable
Traceback (most recent call last):
  File "/opt/plexpy/plexpy/notification_handler.py", line 55, in process_queue
    add_notifier_each(**params)
  File "/opt/plexpy/plexpy/notification_handler.py", line 97, in add_notifier_each
    
  File "/opt/plexpy/plexpy/notification_handler.py", line 172, in notify_conditions
    (stream_data['media_type'] == 'episode' and progress_percent < plexpy.CONFIG.TV_WATCHED_PERCENT))
TypeError: 'bool' object is not callable

**Solution:** In notification_handler.py line 171 is missing an **or** at the end of the line

```
return (plexpy.CONFIG.NOTIFY_CONSECUTIVE or
    (stream_data['media_type']` == 'movie' and progress_percent < plexpy.CONFIG.MOVIE_WATCHED_PERCENT) or
    (stream_data['media_type'] == 'episode' and progress_percent < plexpy.CONFIG.TV_WATCHED_PERCENT))
```

**Comment by JonnyWong16** [comment]
Thanks. Fixed.
