### ISSUE TITLE
Trying to install a second instance of plexpy I'm getting database locked in initial configuration

### ISSUE THREAD

**Issue by cesalo** [Tautulli/Tautulli#1166]
**Version:**
1.4.25
**Branch:**
master
**Operating system:**
Centos 7
**Python version:**
2.7.
**What you did?**
Wanted to try the new beta so I decided to install a separate Plexpy to not affect my current one running in docker.
**What happened?**
I shutdown my docker instance and tried to install a new one. The initial setup went fine but then when it started to show my libraries and initial stats got a "Internal Server" error and it didn't show any data.
**What you expected?**
To be able to install plexpy in Linux.
**How can we reproduce your issue?**

Cloning repo
Running python PlexPy.py
Finish the conf.
I've done these several times and no luck.
**What are your (relevant) settings?**
Centos 7 / Last version of Plex Server.
Also I already have a plexpy instance in docker same version working with no issues.
**Link to logs:**
```
/tautulli/plexpy$ python PlexPy.py
2017-12-18 22:01:23 - INFO :: MainThread : Checking to see if the database has all tables....
2017-12-18 22:01:28 - ERROR :: MainThread : Can't connect to the database: database is locked
2017-12-18 22:01:28 - DEBUG :: MainThread : Generating UUID...
2017-12-18 22:01:28 - INFO :: MainThread : PlexPy Config :: Writing configuration to file
2017-12-18 22:01:28 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /share/media/scripts.1/plex.python/tautulli/plexpy
2017-12-18 22:01:28 - DEBUG :: MainThread : Git output: cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
2017-12-18 22:01:28 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /share/media/scripts.1/plex.python/tautulli/plexpy
2017-12-18 22:01:28 - DEBUG :: MainThread : Git output: master
2017-12-18 22:01:28 - INFO :: MainThread : Retrieving latest version information from GitHub
2017-12-18 22:01:28 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2017-12-18 22:01:28 - DEBUG :: MainThread : Latest version is cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca
2017-12-18 22:01:28 - INFO :: MainThread : PlexPy is up to date
2017-12-18 22:01:28 - INFO :: MainThread : Scheduled background task: Check GitHub for updates
2017-12-18 22:01:28 - INFO :: MainThread : Scheduled background task: Backup PlexPy database
2017-12-18 22:01:28 - INFO :: MainThread : Scheduled background task: Backup PlexPy config
2017-12-18 22:01:28 - INFO :: MainThread : PlexPy WebStart :: Starting PlexPy web server on http://0.0.0.0:8181/
2017-12-18 22:01:45 - INFO :: CP Server Thread-7 : PlexPy PlexTV :: Fetching a new Plex.tv token for PlexPy.
2017-12-18 22:01:46 - INFO :: CP Server Thread-7 : PlexPy Config :: Writing configuration to file
2017-12-18 22:01:46 - INFO :: CP Server Thread-7 : PlexPy PlexTV :: Updated Plex.tv token for PlexPy.
2017-12-18 22:01:46 - INFO :: CP Server Thread-7 : PlexPy Config :: Writing configuration to file
2017-12-18 22:02:01 - INFO :: CP Server Thread-11 : PlexPy Config :: Writing configuration to file
2017-12-18 22:02:02 - INFO :: CP Server Thread-11 : PlexPy PlexTV :: Requesting URLs for server...
2017-12-18 22:02:02 - INFO :: CP Server Thread-11 : PlexPy Config :: Writing configuration to file
2017-12-18 22:02:03 - INFO :: CP Server Thread-11 : PlexPy Config :: Writing configuration to file
2017-12-18 22:02:04 - INFO :: CP Server Thread-11 : PlexPy PlexTV :: Using user-defined URL.
2017-12-18 22:02:04 - INFO :: CP Server Thread-11 : PlexPy Pmsconnect :: Requesting name from server...
2017-12-18 22:02:05 - INFO :: CP Server Thread-11 : PlexPy Config :: Writing configuration to file
2017-12-18 22:02:05 - INFO :: CP Server Thread-11 : PlexPy Pmsconnect :: Server name retrieved.
2017-12-18 22:02:05 - INFO :: CP Server Thread-11 : Scheduled background task: Refresh Plex server URLs
2017-12-18 22:02:05 - INFO :: CP Server Thread-11 : Scheduled background task: Refresh Plex server name
2017-12-18 22:02:05 - INFO :: CP Server Thread-11 : Scheduled background task: Check for active sessions
2017-12-18 22:02:05 - INFO :: CP Server Thread-11 : Scheduled background task: Refresh users list
2017-12-18 22:02:05 - INFO :: CP Server Thread-11 : Scheduled background task: Refresh libraries list
2017-12-18 22:02:05 - INFO :: Thread-12 : PlexPy Pmsconnect :: Requesting libraries list refresh...
2017-12-18 22:02:05 - INFO :: Thread-13 : PlexPy PlexTV :: Requesting users list refresh...
2017-12-18 22:02:05 - DEBUG :: Thread-12 : PlexPy Pmsconnect :: No library data.
2017-12-18 22:02:06 - DEBUG :: Thread-12 : PlexPy Pmsconnect :: No library data.
2017-12-18 22:02:10 - INFO :: CP Server Thread-11 : Re-scheduled background task: Check for active sessions
2017-12-18 22:02:27 - ERROR :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/plextv.py", line 38, in refresh_users
    monitor_db = database.MonitorDatabase()
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/database.py", line 125, in __init__
    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
OperationalError: database is locked

Traceback (most recent call last):
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/plextv.py", line 38, in refresh_users
    monitor_db = database.MonitorDatabase()
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/database.py", line 125, in __init__
    self.connection.execute("PRAGMA journal_mode = %s" % plexpy.CONFIG.JOURNAL_MODE)
sqlite3.OperationalError: database is locked
2017-12-18 22:02:27 - ERROR :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/pmsconnect.py", line 62, in refresh_libraries
    monitor_db = database.MonitorDatabase()
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/database.py", line 123, in __init__
    self.connection.execute("PRAGMA synchronous = OFF")
OperationalError: database is locked

Traceback (most recent call last):
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/logger.py", line 270, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/pmsconnect.py", line 62, in refresh_libraries
    monitor_db = database.MonitorDatabase()
  File "/share/media/scripts.1/plex.python/tautulli/plexpy/plexpy/database.py", line 123, in __init__
    self.connection.execute("PRAGMA synchronous = OFF")
sqlite3.OperationalError: database is locked
```

**Comment by JonnyWong16** [comment]
You can't have two instances of PlexPy/Tautulli sharing the same database. They will conflict with each other.

**Comment by cesalo** [comment]
My current one is running on docker .. they are totally different. The second I was trying to install it from the host server running docker. They are not even sharing any directories.

**Comment by Arcanemagus** [comment]
```
2017-12-18 22:01:28 - ERROR :: MainThread : Can't connect to the database: database is locked
```

For _some_ reason it can't access the database. Either you didn't fully shut down the other one, or the permissions are wrong on the database file. I'm pretty sure that's a different error though.

**Comment by cesalo** [comment]
mmm .. permissions. I using root but it's running in a SAMBA share filesystem from QNAP. The permissions on the files are not from root but It shouldn't affect this since root can read/write files (also I have other scripts like HTPC .. etc .. running in the same way). I see that the database file remains in zero bytes but locked by the python process.
drwxr-xr-x 2 plex plex     0 Dec 18 22:01 backups
-rwxr-xr-x 1 plex plex     0 Dec 18 22:01 plexpy.db
-rwxr-xr-x 1 plex plex    40 Dec 18 22:01 version.lock
I'll try to install it locally and see what happens.
Thanks.

**Comment by cesalo** [comment]
It worked .. locally and validating that permissions were for root. I guess that was the issue.
Thanks.
