### ISSUE TITLE
fails to start as daemon

### ISSUE THREAD

**Issue by hthighway** [Tautulli/Tautulli#12]
trying to run as a daemon, not sure where the issue is

```
user@server:~$ sudo service plexpy start
 * Removing stale /var/run/plexpy/plexpy.pid
 * Starting PlexPy                                  
Traceback (most recent call last):
  File "PlexPy.py", line 220, in <module>
    main()
  File "PlexPy.py", line 155, in main
    plexpy.initialize(config_file)
  File "/opt/plexpy/plexpy/__init__.py", line 167, in initialize
    plextv.refresh_users()
  File "/opt/plexpy/plexpy/plextv.py", line 40, in refresh_users
    pw_db.upsert('plexpy_users', new_value_dict, control_value_dict)
  File "/opt/plexpy/plexpy/db.py", line 111, in upsert
    self.action(update_query, valueDict.values() + keyDict.values())
  File "/opt/plexpy/plexpy/db.py", line 70, in action
    sqlResult = c.execute(query, args)
sqlite3.OperationalError: no such table: plexpy_users                                                                                                        [fail]
```

**Comment by drzoidberg33** [comment]
Is the PlexPy user able to write to your PlexWatch db?

I'm very busy with removing all dependancy on the PW database, but for now PlexPy needs to write to it.

**Comment by hthighway** [comment]
That's probably it, I will check

**Comment by hthighway** [comment]
Backup and running !
