### ISSUE TITLE
Noob issue i´m sure

### ISSUE THREAD

**Issue by ofurpesi** [Tautulli/Tautulli#1213]
Just downloaded the 2.0.13 beta and can´t get it to run :( Here is the content of the log

2018-01-14 08:46:53 - INFO    :: MainThread : Checking if the database upgrades are required...
2018-01-14 08:46:53 - ERROR   :: MainThread : Can't connect to the database: unable to open database file
2018-01-14 08:46:53 - INFO    :: MainThread : Checking if configuration upgrades are required...
2018-01-14 08:46:53 - INFO    :: MainThread : Tautulli Notifiers :: Upgrading to new notification system...
2018-01-14 08:46:53 - INFO    :: MainThread : Tautulli Config :: Writing configuration to file
2018-01-14 08:46:53 - ERROR   :: MainThread : Could not perform upgrades: 'ascii' codec can't decode byte 0xe9 in position 10: ordinal not in range(128)
2018-01-14 08:46:53 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\Pétur Björn\Desktop\plexpy-2.0.13-beta\PlexPy.py", line 266, in <module>
    main()
  File "C:\Users\Pétur Björn\Desktop\plexpy-2.0.13-beta\PlexPy.py", line 192, in main
    plexpy.initialize(config_file)
  File "C:\Users\Pétur Björn\Desktop\plexpy-2.0.13-beta\plexpy\__init__.py", line 172, in initialize
    notifiers.blacklist_logger()
  File "C:\Users\Pétur Björn\Desktop\plexpy-2.0.13-beta\plexpy\notifiers.py", line 575, in blacklist_logger
    db = database.MonitorDatabase()
  File "C:\Users\Pétur Björn\Desktop\plexpy-2.0.13-beta\plexpy\database.py", line 121, in __init__
    self.connection = sqlite3.connect(db_filename(filename), timeout=20)
OperationalError: unable to open database file

Not sure what i´m doing wrong

**Comment by ofurpesi** [comment]
:) It was the characters in my username.

**Comment by ofurpesi** [comment]
Now i´m seeing this after tautilli starts

![image](https://user-images.githubusercontent.com/8067418/34914429-c09a9392-f90a-11e7-9046-a9dc13ef615a.png)

**Comment by ofurpesi** [comment]
All fixed :) got it running using GIT
