### ISSUE TITLE
Won't start, google analytics certificate error

### ISSUE THREAD

**Issue by jasonafernandez** [Tautulli/Tautulli#1257]
**Version:**
v2.0.20-beta (2018-02-24)
**Branch:**
nightly
**Commit hash:**
754fd24
**Operating system:**
Ubuntu 17.10
**Python version:**
Python 2.7.14
**What you did?**
Initially was a git pull to upgrade my nightly version. After upgrade I usually restart plexpy service, except this time, the web session never returned. My Slack alerts were still coming through though, but just unable to access the web site. 

Removed plexpy completely, performed fresh install, git pull -b nightly <.git>. Simply started plexpy, same issue. Output below.

Everything was working fine up until Tuesday Feb 20th when I upgraded.

**What happened?**
Google Chrome trying to access site:

This site can’t be reached
_my plex server hostname_ refused to connect.
Search Google for _my plex server hostname_ 8181
ERR_CONNECTION_REFUSED

Console start:

/opt/plexpy$ sudo python PlexPy.py 
2018-02-24 10:58:33 - INFO :: MainThread : Checking if the database upgrades are required...
2018-02-24 10:58:33 - INFO :: MainThread : Checking if configuration upgrades are required...
2018-02-24 10:58:33 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
2018-02-24 10:58:33 - DEBUG :: MainThread : Git output: 754fd24421ec91560d972e2977c2fb6003f1e42d
2018-02-24 10:58:33 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /opt/plexpy
2018-02-24 10:58:33 - DEBUG :: MainThread : Git output: origin/nightly
2018-02-24 10:58:33 - INFO :: MainThread : Retrieving latest version information from GitHub
2018-02-24 10:58:33 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/nightly
2018-02-24 10:58:33 - DEBUG :: MainThread : Latest version is 754fd24421ec91560d972e2977c2fb6003f1e42d
2018-02-24 10:58:33 - INFO :: MainThread : Tautulli is up to date
2018-02-24 10:58:33 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
2018-02-24 10:58:33 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "PlexPy.py", line 259, in <module>
    main()
  File "PlexPy.py", line 195, in main
    plexpy.start()
  File "/opt/plexpy/plexpy/__init__.py", line 470, in start
    analytics_event(category='system', action='install')
  File "/opt/plexpy/plexpy/__init__.py", line 1725, in analytics_event
    TRACKER.send('event', data)
  File "lib/UniversalAnalytics/Tracker.py", line 245, in send
    self.http.send(data)
  File "lib/UniversalAnalytics/Tracker.py", line 129, in send
    self.open(request)
  File "lib/UniversalAnalytics/Tracker.py", line 105, in open
    return urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 848, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 286, in match_hostname
    % (hostname, dnsnames[0]))
CertificateError: hostname 'www.google-analytics.com' doesn't match '_my plex server hostname_'

Traceback (most recent call last):
  File "PlexPy.py", line 259, in <module>
    main()
  File "PlexPy.py", line 195, in main
    plexpy.start()
  File "/opt/plexpy/plexpy/__init__.py", line 470, in start
    analytics_event(category='system', action='install')
  File "/opt/plexpy/plexpy/__init__.py", line 1725, in analytics_event
    TRACKER.send('event', data)
  File "lib/UniversalAnalytics/Tracker.py", line 245, in send
    self.http.send(data)
  File "lib/UniversalAnalytics/Tracker.py", line 129, in send
    self.open(request)
  File "lib/UniversalAnalytics/Tracker.py", line 105, in open
    return urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 848, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 286, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'www.google-analytics.com' doesn't match '_my plex server hostname_'

**What you expected?**
To start normal.

**How can we reproduce your issue?**
Perform a clean install.

**What are your (relevant) settings?**
Nothing, fresh install, can't even access the initial web config start.

**Link to logs:**
If you need more info please let me know. Not sure what other logs there are.

**Comment by jasonafernandez** [comment]
I was able to resolve the issue by adding the following to my DNS blocker whitelist config.

www.google-analytics.com
ssl.google-analytics.com

Thank you!

**Comment by samwiseg0** [comment]
Same problem. This should be changed. I have blocked google analytics on my network as well. 

EDIT: There needs to be an opt out for google analytics. That should always be an option and it should be off by default.

**Comment by JonnyWong16** [comment]
No, I will be collecting installation analytics by default (Tautulli version and OS), but I will fix it so it doesn't crash.

If you want to disable it, you can set `system_analytics = 0` in the `config.ini` file.

**Comment by samwiseg0** [comment]
> If you want to disable it, you can set system_analytics = 0 in the config.ini file.

That does suffice to be able to opt out. Thanks

**Comment by JonnyWong16** [comment]
~~We can agree to disagree.~~ Sorry, I thought you said "doesn't".

**Comment by jasonafernandez** [comment]
While I agree with Sam; I didn't say it in my initial response, that option does help. Thank you for addressing.

**Comment by samwiseg0** [comment]
> We can agree to disagree. Sorry, I thought you said "doesn't".

no problem. i figured you may have read it that way. I understand why you would want it on by default. At the very least I think there should be documentation of what is collected as well as how to disable it.

**Comment by samwiseg0** [comment]
~~With version 0.2.21 this is still an issue. If I have google analytics blocked the webinterface never starts. Even with the ```system_analytics = 0``` in the config file it fails to start up.~~

~~edit: there is no error in the logs~~

my bad... for some reason the bit was flipped back to 1 instead of 0.

Thanks for all the awesome work

**Comment by JonnyWong16** [comment]
I don't think this has anything to do with analytics. There were a bunch of changes made to the startup scripts between v2.0.20-beta and v2.0.21-beta, so if you're trying to start it as a daemon, double check those scripts and locations.

The original issue has been resolved so I am closing this issue.
