### ISSUE TITLE
Error After Upgrading  2.5 to 2.7

### ISSUE THREAD

**Issue by juhenriquez** [Tautulli/Tautulli#1418]
Get a "500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request." on Home screen

**Steps to Reproduce**
Load Home Screen

**Expected Behavior**
No Error.

**Screenshots**
![image](https://user-images.githubusercontent.com/8250019/115336922-15412f00-a16e-11eb-8184-acd7b0b4cf38.png)

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.7.0]
- Git Branch: [eg. master]
- Git Commit Hash: [eg. c780f1fd6c57763bd0e39253ffc55be2618050ea]
- Platform and Version: [eg. Raspian]
- Python Version: [e.g. 3.7.3]
- Browser and Version: [e.g. Chrome 90.0.4430.72]

**Link to logs (required)**
Log 
<script src="https://gist.github.com/juhenriquez/b3a9acae217d1bb2997cff06a2d03a26.js"></script>

**Comment by JonnyWong16** [comment]
Complete logs not provided.

**Comment by ivoets** [comment]
Got the same error....   

Maybe Python 2 vs  Python 3  error???
Installed Python3  on my QNAP, but don't know if Tautulli calls the right Python version...

Logs error:

HTTP
Traceback (most recent call last):
    File "/share/CACHEDEV1_DATA/.qpkg/PlexPy/plexpy-master/lib/cherrypy/_cprequest.py", line 630, in respond
        self._do_respond(path_info)
    File "/share/CACHEDEV1_DATA/.qpkg/PlexPy/plexpy-master/lib/cherrypy/_cprequest.py", line 689, in _do_respond
        response.body = self.handler()
    File "/share/CACHEDEV1_DATA/.qpkg/PlexPy/plexpy-master/lib/cherrypy/lib/encoding.py", line 221, in __call__
        self.body = self.oldhandler(*args, **kwargs)
    File "/share/CACHEDEV1_DATA/.qpkg/PlexPy/plexpy-master/lib/cherrypy/_cpdispatch.py", line 54, in __call__
        return self.callable(*self.args, **self.kwargs)
    File "/share/CACHEDEV1_DATA/.qpkg/PlexPy/plexpy-master/plexpy/webserve.py", line 399, in home_stats
        stats_count=stats_count)
    File "/share/CACHEDEV1_DATA/.qpkg/PlexPy/plexpy-master/plexpy/datafactory.py", line 314, in get_home_stats
        timestamp = int((datetime.now(tz=plexpy.SYS_TIMEZONE) - timedelta(days=time_range)).timestamp())
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'


Remove & Clean install from .qpkg  solved the problem.

**Comment by JonnyWong16** [comment]
Duplicate #1407.
