### ISSUE TITLE
issue with adding plexwatch.db in 1.1.7v

### ISSUE THREAD

**Issue by miniop** [Tautulli/Tautulli#168]
I tried to import my plexwatch database and there is an error 

Uncaught exception: Traceback (most recent call last):
File "C:\Users\Administrator\Desktop\plexpy-master\plexpy\logger.py", line 210, in new_run
old_run(_args, *_kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "C:\Users\Administrator\Desktop\plexpy-master\plexpy\plexwatch_import.py", line 376, in import_from_plexwatch
import_ignore_interval=import_ignore_interval)
File "C:\Users\Administrator\Desktop\plexpy-master\plexpy\monitor.py", line 355, in write_session_history
metadata['last_viewed_at'], metadata['content_rating'], metadata['summary'], metadata['tagline'],
KeyError: 'tagline'

My database is huge 228mb :)

**Comment by drzoidberg33** [comment]
I know what the issue is here, it's something that was added in the latest release. I'll push out a fix for this.

**Comment by miniop** [comment]
thanks let me know so i can try it and report back

**Comment by drzoidberg33** [comment]
Fixed in https://github.com/drzoidberg33/plexpy/commit/e5ce57feadc956478acf55d7e6e369d1f5c8f9e9

This will be pushed to the master branch on next release.
