### ISSUE TITLE
API Error. cannot import name db

### ISSUE THREAD

**Issue by bgulla** [Tautulli/Tautulli#225]
Just enabled api and when I try to hit any endpoint, I get the following error. 

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/plexpy/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/plexpy/plexpy/webserve.py", line 616, in api
    from plexpy.api import Api
  File "/opt/plexpy/plexpy/api.py", line 16, in <module>
    from plexpy import db, cache, versioncheck, logger, helpers
ImportError: cannot import name db

**Comment by Hellowlol** [comment]
Thats feltovers from headphones. There isnt much to see in the api until https://github.com/drzoidberg33/plexpy/pull/200 is merged

**Comment by drzoidberg33** [comment]
The api is back since 1.2.2.
