### ISSUE TITLE
If "Local" is playing media, then "Activity" returns a 500 Internal Server Error.

### ISSUE THREAD

**Issue by iAmMrinal0** [Tautulli/Tautulli#33]
Similar to #32, tries to get an ID for "Local" but it returns `None`

```
Traceback (most recent call last):
  File "lib/cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "G:\GitHub\plexpy\plexpy\webserve.py", line 620, in get_current_activity_header
    result = pms_connect.get_current_activity()
  File "G:\GitHub\plexpy\plexpy\pmsconnect.py", line 489, in get_current_activity
    session_output = self.get_session_each(session_type, session)
  File "G:\GitHub\plexpy\plexpy\pmsconnect.py", line 660, in get_session_each
    'user_id': user_details['user_id'],
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I mostly play my media via DLNA on my Bravia TV, which does not have a Plex app and those plays show up as 'Local' and monitoring fails.
![screenshot 5](https://cloud.githubusercontent.com/assets/890062/8889404/9cdb85b4-32f7-11e5-8882-717e50bf3a00.png)
And the `settings` link in the error message is linked to 'config' which has been removed.

**Comment by drzoidberg33** [comment]
Thanks for the report. I've never tested without authentication before so wasn't aware of this issue. Will issue a fix.

**Comment by drzoidberg33** [comment]
I addressed this issue in https://github.com/drzoidberg33/plexpy/commit/2a613c117f6e6df9d1675be3189804621cfc1c49

Please check if it works on your end.

**Comment by iAmMrinal0** [comment]
Works now! :+1: :ok_hand:
