### ISSUE TITLE
v.1.2.8 problem

### ISSUE THREAD

**Issue by miniop** [Tautulli/Tautulli#332]
When i try to browse a user stats i am geting this error : 

 Player Stats
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\plexpy-master\lib/cherrypy_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\plexpy-master\lib/cherrypy\lib\encoding.py", line 217, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\plexpy-master\lib/cherrypy_cpdispatch.py", line 61, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\plexpy-master\plexpy\webserve.py", line 871, in get_user_player_stats
    result = user_data.get_user_player_stats(user_id=user_id, user=user)
  File "C:\plexpy-master\plexpy\users.py", line 541, in get_user_player_stats
    player = helpers.sanitize(item[0])
  File "C:\plexpy-master\plexpy\helpers.py", line 436, in sanitize
    return str(string).replace('<','&lt;').replace('>','&gt;')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 5: ordinal not in range(128)

Powered by CherryPy 3.8.0

When i try to see the ip address and History of this user getting : 

DataTables warning: table id=user_ip_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by maxjeansto** [comment]
i have exactly the same problem miniop with the 1.2.8 update

**Comment by drzoidberg33** [comment]
I'm working on a fix.

**Comment by drzoidberg33** [comment]
Please check v1.2.9.

**Comment by miniop** [comment]
Fixed thanks
