### ISSUE TITLE
SyntaxError in datatables.py on startup.

### ISSUE THREAD

**Issue by nzurku** [Tautulli/Tautulli#341]
Getting this on either an update or a fresh install from git.

Traceback (most recent call last):
  File "PlexPy.py", line 25, in <module>
    from plexpy import webstart, logger, web_socket
  File "/opt/plexpy/plexpy/**init**.py", line 34, in <module>
    from plexpy import versioncheck, logger, activity_pinger, plextv, pmsconnect
  File "/opt/plexpy/plexpy/activity_pinger.py", line 16, in <module>
    from plexpy import logger, pmsconnect, plextv, notification_handler, database, helpers, activity_processor
  File "/opt/plexpy/plexpy/pmsconnect.py", line 16, in <module>
    from plexpy import logger, helpers, users, http_handler, common
  File "/opt/plexpy/plexpy/users.py", line 16, in <module>
    from plexpy import logger, datatables, common, database, helpers
  File "/opt/plexpy/plexpy/datatables.py", line 190
    result = [{k: helpers.sanitize(v) if isinstance(v, basestring) else v for k, v in row.iteritems()}
                                                                            ^
SyntaxError: invalid syntax

**Comment by drzoidberg33** [comment]
Which version of Python are you using?

PlexPy requires Python 2.7.

**Comment by nzurku** [comment]
That as my issue, had to update Python.

Thanks!
