### ISSUE TITLE
PlexPy keeps crashing?

### ISSUE THREAD

**Issue by vulcanjedi** [Tautulli/Tautulli#404]
Suddenly PlexPy has repeatedly started crashing. Previously couldn't even ssh until physically power cycling host node. after updating to latest rev still eventually crashes. Reboots seems to revert to stable state briefly. Upon booting, any new updates have not been retained. Says I'm 36 changes behind.  

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/plexpy/plexpy/webserve.py", line 141, in home_stats
    notify_watched_percent=notify_watched_percent)
  File "/opt/plexpy/plexpy/datafactory.py", line 153, in get_home_stats
    monitor_db = database.MonitorDatabase()
  File "/opt/plexpy/plexpy/database.py", line 63, in **init**
    self.connection.execute("PRAGMA synchronous = OFF")
OperationalError: disk I/O error

**Comment by JonnyWong16** [comment]
What OS are you running? Do you have read/write access to the PlexPy folder?

Try this: https://github.com/drzoidberg33/plexpy/wiki/Troubleshooting#solution
It's a different problem, but it might fix your problem as well.

**Comment by vulcanjedi** [comment]
Hi JonnyWong16, thanks for all you guys' dev work on this great notifier. I'm more of a linux novice but can manage to get around.
I am running Raspbian (debian). PlexPy has been working fine for a long time, I dont ever mess with this system aside from the native PlexPy updater.
The other day I noticed the Pushbullet notifications stopped over the holidays and had my roommate power cycle the Pi when I discovered PlexPy was having issues.

drwxr-xr-x  4 root root 4096 May  6  2015 minecraft-pi
drwxrwxrwx 10 pi   root 4096 Dec 27 21:25 plexpy
drwxrwxrwx  3 root root 4096 Dec 27 21:28 plexWatch
drwxr-xr-x  5 root root 4096 May  6  2015 sonic-pi
drwxr-xr-x  7 root root 4096 May  6  2015 vc

**Comment by JonnyWong16** [comment]
I'm not to familiar with Debian, but the permissions look ok.

First try to do a manual update using `git pull` in the PlexPy directory. Maybe check that Python is up to date as well.

**Comment by drzoidberg33** [comment]
> OperationalError: disk I/O error

That's never a good sign. The fact that the entire box freezes up too indicates to me that there something wrong with the box, possibly a bad disk.

**Comment by vulcanjedi** [comment]
its actually only completely locked up (unable to ssh) once. Otherwise able to ssh/reboot it. Maybe I'll see if I can find another sd card lying around and clone/reinstall.
For instance just woke up today and encountered this on the webpage 

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/plexpy/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/plexpy/plexpy/webserve.py", line 76, in home
  File "/opt/plexpy/plexpy/webserve.py", line 52, in serve_template
  File "/opt/plexpy/lib/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/opt/plexpy/lib/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/opt/plexpy/lib/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/opt/plexpy/lib/mako/runtime.py", line 860, in _exec_template
    callable_(context, _args, *_kwargs)
  File "memory:0xee8ad0", line 44, in render_body
  File "/opt/plexpy/lib/mako/exceptions.py", line 76, in **init**
    self.records = self._init(traceback)
  File "/opt/plexpy/lib/mako/exceptions.py", line 156, in _init
    encoding = util.parse_encoding(fp)
  File "/opt/plexpy/lib/mako/util.py", line 231, in parse_encoding
    parser.suite(line1.decode('ascii', 'ignore'))
TypeError: suite() argument 1 must be string without null bytes, not unicode
Powered by CherryPy 3.8.0

**Comment by JonnyWong16** [comment]
Did you figure this out?

Reopen the issue if it is still a problem.
