### ISSUE TITLE
Error while checking version

### ISSUE THREAD

**Issue by ooii** [Tautulli/Tautulli#43]
Hi,
I have the following error when I start plexpy. It seems it happens when checking for new versions.

```
05-aoû-2015 11:57:38 - INFO :: MainThread : Checking to see if the database has all tables....
05-aoû-2015 11:57:38 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /Users/farid/plexpy
05-aoû-2015 11:57:38 - DEBUG :: MainThread : Git output: fa782641efbb624bae312f98d9d063b2b7eaf9ea
05-aoû-2015 11:57:38 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /Users/farid/plexpy
05-aoû-2015 11:57:38 - DEBUG :: MainThread : Git output: master
05-aoû-2015 11:57:38 - INFO :: MainThread : Retrieving latest version information from GitHub
05-aoû-2015 11:57:38 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
Logged from file versioncheck.py, line 134
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
Logged from file versioncheck.py, line 134
05-aoû-2015 11:57:39 - INFO :: MainThread : PlexPy is up to date
05-aoû-2015 11:57:39 - INFO :: MainThread : Requesting URLs for server...
05-aoû-2015 11:57:39 - INFO :: MainThread : Writing configuration to file
05-aoû-2015 11:57:39 - INFO :: MainThread : Writing configuration to file
05-aoû-2015 11:57:39 - INFO :: MainThread : Requesting users list refresh...
05-aoû-2015 11:57:42 - INFO :: MainThread : Users list refreshed.
05-aoû-2015 11:57:42 - INFO :: MainThread : Starting PlexPy web server on http://0.0.0.0:8080/
05-aoû-2015 11:57:42 - INFO :: MainThread : Scheduled background task: Check GitHub for updates
05-aoû-2015 11:57:42 - INFO :: MainThread : Scheduled background task: Refresh Plex Server URLs
05-aoû-2015 11:57:42 - INFO :: MainThread : Scheduled background task: Check for active sessions
05-aoû-2015 11:57:42 - INFO :: MainThread : Scheduled background task: Refresh users list
``
```

**Comment by drzoidberg33** [comment]
Sorry I'm not sure what's happening here, I'll have to investigate. This code hasn't changed at all from the original code from Headphones, so it must be something new.

What language is your system set to?

**Comment by ooii** [comment]
I'm using french in my system.

**Comment by drzoidberg33** [comment]
Thank you. I'll look into this when I get a moment.

**Comment by zenjabba** [comment]
I'm getting this error when I run it on my QNAP device

12-Aug-2015 14:09:56 - DEBUG :: MainThread : Git output: a039641aba69b9d09aaebdb7f177567cd383c9e8
12-Aug-2015 14:09:56 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /share/CACHEDEV1_DATA/.qpkg/Optware/plexpy
12-Aug-2015 14:09:56 - DEBUG :: MainThread : Git output: master
12-Aug-2015 14:09:56 - INFO :: MainThread : Retrieving latest version information from GitHub
12-Aug-2015 14:09:56 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
12-Aug-2015 14:09:57 - ERROR :: MainThread : Unable to connect to remote host because of a SSL error. It is likely that your system cannot verify the validityof the certificate. The remote certificate is either self-signed, or the remote server uses SNI. See the wiki for more information on this topic.
12-Aug-2015 14:09:57 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?

**Comment by drzoidberg33** [comment]
@zenjabba That error is unrelated to this issue. I need to enable an option to disable SSL checking. Your issue is detailed here: http://docs.python-requests.org/en/latest/community/faq/#what-are-hostname-doesn-t-match-errors

**Comment by drzoidberg33** [comment]
Is this still an issue?

**Comment by ooii** [comment]
Nope. Should have closed it before. I do it right now.
