### ISSUE TITLE
PlexPy stopped working

### ISSUE THREAD

**Issue by pax0707** [Tautulli/Tautulli#442]
I have a feeling something broke.

```
14-sij-2016 18:48:37 - ERROR :: MainThread : Uncaught exception: Traceback (most
 recent call last):
  File "plexpy.py", line 232, in <module>
    main()
  File "plexpy.py", line 157, in main
    plexpy.initialize(config_file)
  File "D:\Plex\PlexPy\plexpy\__init__.py", line 86, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "D:\Plex\PlexPy\plexpy\config.py", line 401, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "1".

Traceback (most recent call last):
  File "plexpy.py", line 232, in <module>
    main()
  File "plexpy.py", line 157, in main
    plexpy.initialize(config_file)
  File "D:\Plex\PlexPy\plexpy\__init__.py", line 86, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "D:\Plex\PlexPy\plexpy\config.py", line 401, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
configobj.ParseError: Invalid line at line "1".
```

**Comment by Hellowlol** [comment]
Messed up the configure file?

**Comment by pax0707** [comment]
Yeah, looks like it.
Config file is garbage.

There was a power outage while I was at work...
