### ISSUE TITLE
PlexPy no longer launching

### ISSUE THREAD

**Issue by alternativesurfer** [Tautulli/Tautulli#444]
Just noticed I am unable to view plexpy, signed into my server and found the application keeps force quitting as soon as I attempt to launch it.
Nothing showing up in the logs (just the last info recorded before this issue occurred)....
Any ideas?  What am I missing???

I made sure GIT was updated (and re-confirmed that through setup I selected this:
- Run the installer, select all the defaults except for the section called "Adjusting your PATH environment" - here select "Use Git from the Windows command prompt"

```
14-Jan-2016 08:47:43 - DEBUG   :: Thread-13 : PlexPy ActivityProcessor :: ratingKey 99815 not logged. Does not meet logging criteria. Media type is 'track'
14-Jan-2016 09:56:42 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231006 has been added to Plex.
14-Jan-2016 10:57:43 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231007 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231010 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231011 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231012 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231013 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231014 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231015 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231016 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231017 has been added to Plex.
14-Jan-2016 11:09:44 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231018 has been added to Plex.
14-Jan-2016 11:10:43 - DEBUG   :: Thread-19 : PlexPy Monitor :: Library item 231019 has been added to Plex.
14-Jan-2016 11:10:44 - DEBUG   :: Thread-19 : PlexPy Monitor :: Library item 231020 has been added to Plex.
14-Jan-2016 11:18:42 - DEBUG   :: Thread-16 : PlexPy Monitor :: Library item 231021 has been added to Plex.
14-Jan-2016 11:26:42 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231022 has been added to Plex.
14-Jan-2016 11:36:42 - DEBUG   :: Thread-15 : PlexPy Monitor :: Library item 231023 has been added to Plex.
14-Jan-2016 11:47:46 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231031 has been added to Plex.
14-Jan-2016 11:47:46 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231032 has been added to Plex.
14-Jan-2016 11:47:46 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231033 has been added to Plex.
14-Jan-2016 11:47:47 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231034 has been added to Plex.
14-Jan-2016 11:47:47 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231035 has been added to Plex.
14-Jan-2016 11:47:47 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231036 has been added to Plex.
14-Jan-2016 11:47:49 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231029 has been added to Plex.
14-Jan-2016 11:47:49 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231030 has been added to Plex.
14-Jan-2016 11:47:51 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231025 has been added to Plex.
14-Jan-2016 11:47:51 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231026 has been added to Plex.
14-Jan-2016 11:47:51 - DEBUG   :: Thread-18 : PlexPy Monitor :: Library item 231027 has been added to Plex.
14-Jan-2016 11:57:44 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231042 has been added to Plex.
14-Jan-2016 11:57:44 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231043 has been added to Plex.
14-Jan-2016 11:57:44 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231044 has been added to Plex.
14-Jan-2016 11:57:44 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231045 has been added to Plex.
14-Jan-2016 11:57:45 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231037 has been added to Plex.
14-Jan-2016 11:57:45 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231038 has been added to Plex.
14-Jan-2016 11:57:45 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231039 has been added to Plex.
14-Jan-2016 11:57:45 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231040 has been added to Plex.
14-Jan-2016 11:57:45 - DEBUG   :: Thread-21 : PlexPy Monitor :: Library item 231041 has been added to Plex.
```

**Comment by JonnyWong16** [comment]
The command window just closes when you try to run PlexPy.py?

Try starting PlexPy from the command prompt with `python PlexPy.py` so you can see the output.

**Comment by alternativesurfer** [comment]
This is my output:

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.
I:\PlexPy>plexpy.py
Traceback (most recent call last):
  File "I:\PlexPy\PlexPy.py", line 25, in <module>
    from plexpy import webstart, logger, web_socket
  File "I:\PlexPy\plexpy\__init__.py", line 20, in <module>
    import sqlite3
  File "C:\Python27\lib\sqlite3\__init__.py", line 24, in <module>
    from dbapi2 import *
  File "C:\Python27\lib\sqlite3\dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

I:\PlexPy>
```

**Comment by JonnyWong16** [comment]
Things to check:
- Make sure you have the correct 32-bit or 64-bit latest version Python 2.7.11
- Try this https://github.com/drzoidberg33/plexpy/wiki/Troubleshooting#solution

**Comment by alternativesurfer** [comment]
Thank you so much!
That did it, there was an outdated sqllite dll that somehow got in there...
