### ISSUE TITLE
There was an error communicating with your Plex Server

### ISSUE THREAD

**Issue by tdkoning93** [Tautulli/Tautulli#450]
2016-01-17 18:33:44 WARNING Unable to parse XML for get_sessions.
2016-01-17 18:33:44 WARNING Error parsing XML. not well-formed (invalid token): line 36, column 162

**Comment by tdkoning93** [comment]
Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 260, in __call__
    ct.params['charset'] = self.find_acceptable_charset()
  File "lib/cherrypy/lib/encoding.py", line 161, in find_acceptable_charset
    if encoder(encoding):
  File "lib/cherrypy/lib/encoding.py", line 110, in encode_string
    for chunk in self.body:
TypeError: 'bool' object is not iterable

Its either someones device name with the letter "ë" or an username with "_" in it.

**Comment by drzoidberg33** [comment]
Duplicate here: https://github.com/drzoidberg33/plexpy/issues/212
