### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by skjnldsv** [Tautulli/Tautulli#456]
Hi, I'm using Archlinux 4.3.3-2-ARCH.
I'm using this package: https://aur.archlinux.org/packages/plexpy/
Unfortunately, when enabled, the systemd doesn't start the plexpy service.  Instead I get the error bellow. If I restart it after my login, it works. Don't know really why. :/

Thanks for your work anyway, it's a really good app! ;)

```
python2[2953]: plexpy.service: Executing: /usr/bin/python2 /opt/plexpy/PlexPy.py --quiet --daemon --nolaunch --config /var/lib/plexpy/config.ini --datadir /var/lib/plexpy --nolaunch
python2[2953]: Traceback (most recent call last):
python2[2953]: File "/opt/plexpy/PlexPy.py", line 232, in <module>
python2[2953]: main()
python2[2953]: File "/opt/plexpy/PlexPy.py", line 157, in main
python2[2953]: plexpy.initialize(config_file)
python2[2953]: File "/opt/plexpy/plexpy/__init__.py", line 172, in initialize
python2[2953]: pmsconnect.get_server_friendly_name()
python2[2953]: File "/opt/plexpy/plexpy/pmsconnect.py", line 24, in get_server_friendly_name
python2[2953]: server_name = PmsConnect().get_server_pref(pref='FriendlyName')
python2[2953]: File "/opt/plexpy/plexpy/pmsconnect.py", line 1292, in get_server_pref
python2[2953]: prefs = self.get_server_prefs(output_format='xml')
python2[2953]: File "/opt/plexpy/plexpy/pmsconnect.py", line 172, in get_server_prefs
python2[2953]: output_format=output_format)
python2[2953]: File "/opt/plexpy/plexpy/http_handler.py", line 83, in make_request
python2[2953]: logger.warn(u"Failed to access uri endpoint %s with error %s" % (uri, e))
python2[2953]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
```

**Comment by JonnyWong16** [comment]
Do you have any special characters in your server name?

**Comment by skjnldsv** [comment]
I don't use a server name.

**Comment by skjnldsv** [comment]
All clear now!
