### ISSUE TITLE
Clean install on Mac OS El Capitan Error/Not running

### ISSUE THREAD

**Issue by a1000ydStare** [Tautulli/Tautulli#463]
Clean install of PlexPy using git on El Capitan.  When I first run after setup wizard completes, I get this:

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/PlexPy/plexpy/webserve.py", line 156, in library_stats
    server_libraries = server_children['libraries_list']
TypeError: list indices must be integers, not str

2016-01-22 11:15:43 WARNING Unable to retrieve data.
2016-01-22 11:15:43 WARNING Unable to parse XML for get_recently_added.
2016-01-22 11:15:43 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=8 with error timed out
2016-01-22 11:15:43 WARNING Unable to retrieve data.
2016-01-22 11:15:43 WARNING Unable to parse XML for get_libraries_list.
2016-01-22 11:15:43 WARNING Unable to parse XML for get_sessions.
2016-01-22 11:15:43 WARNING Failed to access uri endpoint /library/sections with error timed out
2016-01-22 11:15:43 WARNING Failed to access uri endpoint /status/sessions with error timed out
2016-01-22 11:15:43 WARNING Unable to parse XML for get_sessions.
2016-01-22 11:15:43 WARNING Failed to access uri endpoint /status/sessions with error timed out
2016-01-22 11:15:38 WARNING Unable to parse XML for get_sessions.
2016-01-22 11:15:38 WARNING Unable to retrieve data.
2016-01-22 11:15:38 WARNING Failed to access uri endpoint /status/sessions with error [Errno 64] Host is down
2016-01-22 11:15:38 WARNING Unable to parse XML for get_sessions.
2016-01-22 11:15:38 WARNING Failed to access uri endpoint /status/sessions with error [Errno 65] No route to host
2016-01-22 11:15:24 WARNING Unable to retrieve data.
2016-01-22 11:15:24 WARNING Unable to parse XML for get_recently_added.
2016-01-22 11:15:24 WARNING Failed to access uri endpoint /library/recentlyAdded?X-Plex-Container-Start=0&X-Plex-Container-Size=6 with error [Errno 64] Host is down
2016-01-22 11:15:23 WARNING Unable to retrieve data.
2016-01-22 11:15:23 WARNING Unable to parse XML for get_sessions.
2016-01-22 11:15:23 WARNING Failed to access uri endpoint /status/sessions with error [Errno 64] Host is down
2016-01-22 11:15:23 WARNING Unable to parse XML for get_libraries_list.
2016-01-22 11:15:23 WARNING Unable to parse XML for get_sessions.
2016-01-22 11:15:23 WARNING Failed to access uri endpoint /library/sections with error [Errno 64] Host is down
2016-01-22 11:15:23 WARNING Failed to access uri endpoint /status/sessions with error [Errno 64] Host is down
2016-01-22 11:15:20 INFO    Scheduled background task: Refresh users list
2016-01-22 11:15:20 INFO    Scheduled background task: Check for active sessions
2016-01-22 11:15:20 INFO    Scheduled background task: Refresh Plex Server Name
2016-01-22 11:15:20 INFO    Scheduled background task: Refresh Plex Server URLs
2016-01-22 11:15:20 INFO    Scheduled background task: Check GitHub for updates
2016-01-22 11:15:19 INFO    Web server authentication is enabled, username is 'keith'
2016-01-22 11:15:19 INFO    Starting PlexPy web server on https://0.0.0.0:8181/
2016-01-22 11:15:19 INFO    Users list refreshed.
2016-01-22 11:15:18 INFO    Requesting users list refresh...
2016-01-22 11:15:18 WARNING Unable to parse XML for get_server_list.
2016-01-22 11:15:18 WARNING Failed to access uri endpoint /servers with error [Errno 64] Host is down
2016-01-22 11:15:18 WARNING Unable to parse XML for get_local_server_name.
2016-01-22 11:15:18 WARNING Failed to access uri endpoint /:/prefs with error timed out
2016-01-22 11:15:08 INFO    Requesting name from server...
2016-01-22 11:15:08 INFO    Server URL retrieved.
2016-01-22 11:15:08 INFO    Writing configuration to file
2016-01-22 11:15:08 INFO    Server URL retrieved.
2016-01-22 11:15:08 INFO    Writing configuration to file
2016-01-22 11:15:07 INFO    Writing configuration to file
2016-01-22 11:15:07 INFO    Requesting URLs for server...
2016-01-22 11:15:07 INFO    PlexPy is up to date
2016-01-22 11:15:07 DEBUG   Latest version is 9409303f249e8ca854cba9362c2f8a2a9a51d0b7
2016-01-22 11:15:06 DEBUG   Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
2016-01-22 11:15:06 INFO    Retrieving latest version information from GitHub
2016-01-22 11:15:06 DEBUG   Git output: master

Any help is greatly appreciated!

**Comment by a1000ydStare** [comment]
Also, to add, I've verified IP in Plex Media Server and token appears to be correct since I get my users/friends list.  Tried reinstalling as well as trying the dev version (which didn't run for me at all)

**Comment by JonnyWong16** [comment]
What is the SSL setting on your Plex server? (preferred, required?)

Can you access any of those endpoints?

```
https://pms_ip:32400/satus/sessions?X-Plex-Token=your_plex_token
https://pms_ip:32400/library/sections?X-Plex-Token=your_plex_token
https://pms_ip:32400/library/recentlyAdded?X-Plex-Token=your_plex_token
```

**Comment by a1000ydStare** [comment]
I have it set to required.  Tried accessing those links with my info, all just produced a blank page.

Set it to preferred and same thing (I tried http and https both ways) still just a blank page.

Thank you!

**Comment by JonnyWong16** [comment]
Local or remote server?

**Comment by a1000ydStare** [comment]
Local.  I tried remote as well using my external ip same thing.

I also have Force SSL on.  Remote access is enabled and working fine for plex users.

**Comment by didyouexpectthat** [comment]
I have this issue on a fresh install of Debian 8.
I am using plexpy locally with 2 PMS servers (two containers). I have preferred HTTPS on my Plex servers, but HTTPS is not enabled in plexpy for connecting to PMS. I am connecting to plexpy over HTTPS. 
I get this when it is trying to pull library statistics. watch statistics are okay.
Each plex server is 0.9.15.1 at time of writing.
Only one server has the issue, and it is the server that just has TV shows. The movies only server is completely fine with showing this same statistic.
I am able to access the URLs you had in the previous comment over HTTP and HTTPs without problem.

```
Library Statistics plex-tv

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/plexpy/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/plexpy/plexpy/webserve.py", line 164, in library_stats
    stats_data = pms_connect.get_library_stats(library_cards=library_cards)
  File "/opt/plexpy/plexpy/pmsconnect.py", line 1432, in get_library_stats
    if library_list['library_count'] != '0':
TypeError: list indices must be integers, not str
Powered by CherryPy 3.8.0
```

When I check plexpy log,

```
2016-01-23 06:21:26 WARNING Unable to parse XML for get_library_children.
2016-01-23 06:21:26 WARNING Failed to access uri endpoint /library/sections/1/all?X-Plex-Container-Start=0&X-Plex-Container-Size=1&type=2 with error timed out
2016-01-23 06:18:22 WARNING Unable to parse XML for get_library_children.
2016-01-23 06:18:22 WARNING Failed to access uri endpoint /library/sections/3/all?X-Plex-Container-Start=0&X-Plex-Container-Size=1&type=2 with error timed out
```

I only have 2 libraries on my TV server. One is very large, over 1000 TV shows. The other is an anime with 50 shows. If I just try to show TV shows, I get this error. If I do just the anime, it shows up just fine.
Is the timeout too short for large libaries?

**Comment by didyouexpectthat** [comment]
Update: there were about a lot of commits posted today. I upgraded to the latest and I do not appear to get this error anymore with all of the libraries selected.

**Comment by a1000ydStare** [comment]
Just tried what didyouexpectthat did; updated to latest master version and still same problem.  

Tried wiping and reinstalling and produced the results.  All these attempts were using my internal LAN IP.   I reinstalled and reran wizard and this time selected my external ip and selected remote server and it worked!  Not sure why and I'd be willing to test more if the dev thinks it would be helpful.

Also can the dev post his paypal info? I'd like to contribute a cup of coffee to the cause.

**Comment by JonnyWong16** [comment]
There must be some problem with the way your internal network is setup that's cause connection issues between PlexPy and your Plex server.

My donation link can be found in my [forum signature](http://forums.plex.tv/discussion/comment/1112656/#Comment_1112656).

I'm going to close this since it seem like it has been resolved.
