### ISSUE TITLE
Script notify bug

### ISSUE THREAD

**Issue by martinorob** [Tautulli/Tautulli#471]
Hi, the script notify works very well but i have found a bug (i think).

This is the error log:

Uncaught exception: Traceback (most recent call last):
File "/usr/local/plexpy/plexpy/logger.py", line 221, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.**target(_self.__args, *_self.__kwargs)
File "/usr/local/plexpy/plexpy/notification_handler.py", line 56, in notify
script_args=notify_strings[2])
File "/usr/local/plexpy/plexpy/notifiers.py", line 473, in send_notification
scripts.notify(message=body, subject=subject, **kwargs)
File "/usr/local/plexpy/plexpy/notifiers.py", line 1908, in notify
cwd=plexpy.CONFIG.SCRIPTS_FOLDER)
File "/usr/lib/python2.7/subprocess.py", line 710, in __init**
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
TypeError: execv() arg 2 must contain only strings
2016-01-24 13:59:16 DEBUG   PlexPy Notifiers :: Full script is: ['php', u'/volume1/Plex/scripts/play.php', u'"M@rtino"', u'"Apple TV"', u'"Gazebo Gioved\xec [2016-01-21 h23-10 Rai 3]"']

The problem is the accented i that is reported as \xec and crash the notifier!

Thanks for your support!

M.

**Comment by Hellowlol** [comment]
What locale is your system set to?

**Comment by martinorob** [comment]
Synology> locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
Synology> 

locale -a
C
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
en_US.utf8
es_ES.utf8
fr_FR.utf8
hu_HU.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
sv_SE.utf8
tr_TR.utf8
zh_CN.utf8
zh_TW.utf8

**Comment by Hellowlol** [comment]
The double quotes has been removed so I think it should be parsed as a string now. Can you verify?

**Comment by JonnyWong16** [comment]
Reopen if this is still an issue.

**Comment by gklka** [comment]
I believe I still have this bug:

```
PlexPy Notifiers :: Full script is: ['python', u'/opt/plexstatus/scripts/notification.py', u'--action', u'Play', u'--title', u'\xcdgy j\xe1rtam any\xe1tokkal - T\xedz alkalom', u'--user', u'Korodinora', u'--count', u'1', u'--poster', u'http://i.imgur.com/mfDZnWw.jpg']
```

```
Uncaught exception: Traceback (most recent call last):
    File "/opt/plexpy/plexpy/logger.py", line 270, in new_run 
        old_run(*args, **kwargs) 
    File "/usr/lib/python2.7/threading.py", line 763, in run 
        self.__target(*self.__args, **self.__kwargs) 
    File "/opt/plexpy/plexpy/notifiers.py", line 2208, in run_script 
        cwd=self.script_folder) 
    File "/usr/lib/python2.7/subprocess.py", line 710, in __init__ 
        errread, errwrite) 
    File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child 
        raise child_exception 
TypeError: execv() arg 2 must contain only strings 
```

My locale settings are very similar:

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by Hellowlol** [comment]
@gklka what os is this on?

**Comment by gklka** [comment]
Ubuntu 14.10
