### ISSUE TITLE
Issue uploading to imgur

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#559]
When adding a movie/tv to test the poster function, received the following error. It does not send a push message at all

> - Poster: {poster_url} 
>   <movie>Movie: {title} ({year})</movie><tv>TV: {title} {show_name} {episode_name} (S{season_num}E{episode_num})</tv> <music>Music: {artist_name} - {album_name}</music> 
> - Library: {library_name}
> - Rating:     {rating} 
> - Tagline:    {tagline} 
> - Duration:    {duration} mins.
> - IMDB: {imdb_url}
> - The TVDB: {thetvdb_url}
> - Summary: {summary}> 

Error message in log:
`Uncaught exception: Traceback (most recent call last):
File "/opt/plexpy/plexpy/logger.py", line 221, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/plexpy/plexpy/notification_handler.py", line 230, in notify_timeline
notify_strings = build_notify_text(timeline=timeline_data, state=notify_action)
File "/opt/plexpy/plexpy/notification_handler.py", line 519, in build_notify_text
metadata['poster_url'] = helpers.uploadToImgur(os.path.join(plexpy.CONFIG.CACHE_DIR, 'cache-poster.jpg'), full_title)
File "/opt/plexpy/plexpy/helpers.py", line 550, in uploadToImgur
response = urllib2.urlopen(request)
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 437, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 475, in error
return self._call_chain(*args)
File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request`

`ERROR  Uncaught exception: Traceback (most recent call last):
File "/opt/plexpy/plexpy/logger.py", line 221, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/plexpy/plexpy/notification_handler.py", line 230, in notify_timeline
notify_strings = build_notify_text(timeline=timeline_data, state=notify_action)
File "/opt/plexpy/plexpy/notification_handler.py", line 519, in build_notify_text
metadata['poster_url'] = helpers.uploadToImgur(os.path.join(plexpy.CONFIG.CACHE_DIR, 'cache-poster.jpg'), full_title)
File "/opt/plexpy/plexpy/helpers.py", line 550, in uploadToImgur
response = urllib2.urlopen(request)
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 437, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 475, in error
return self._call_chain(*args)
File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request`

**Comment by JonnyWong16** [comment]
Fixed in v1.3.8.
