### ISSUE TITLE
Cannot setup Notification Agents - Pushbullet & Pushover

### ISSUE THREAD

**Issue by zhazell** [Tautulli/Tautulli#574]
Hello,

I just downloaded and installed PlexPy on my QNAP NAS and it works fantastically. I wanted to setup some notification agents and was looking into pushbullet and Pushover so I can get push notifications on my iPhone. However when I try and setup either of these services and input the API key, I immediately get an error when I tab off that field that covers the entire screen. See below. Exact error on both. 

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "/share/MD1_DATA/.qpkg/PlexPy/plexpy-master/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/share/MD1_DATA/.qpkg/PlexPy/plexpy-master/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/share/MD1_DATA/.qpkg/PlexPy/plexpy-master/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/share/MD1_DATA/.qpkg/PlexPy/plexpy-master/plexpy/webserve.py", line 1370, in get_notification_agent_config
    config = notifiers.get_notification_agent_config(agent_id=agent_id)
  File "/share/MD1_DATA/.qpkg/PlexPy/plexpy-master/plexpy/notifiers.py", line 385, in get_notification_agent_config
    return pushbullet.return_config_options()
  File "/share/MD1_DATA/.qpkg/PlexPy/plexpy-master/plexpy/notifiers.py", line 982, in return_config_options
    'select_options': self.get_devices()
  File "/share/MD1_DATA/.qpkg/PlexPy/plexpy-master/plexpy/notifiers.py", line 948, in get_devices
    'Authorization': 'Basic %s' % base64.b64encode(plexpy.CONFIG.PUSHBULLET_APIKEY + ":")})
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/share/MD1_DATA/.qpkg/PlexPy/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
Powered by CherryPy 3.8.0
```

It looks like it has something to do with a certificate verify failed. Possibly due to the lack of root CAs on the QNAP hence whey I had to set "verify_ssl_cert = 0" Any correlation? 

Also I cannot clear this error. When I try and go back to the config window for these agents, I get the error again and cannot clear the field. 

Great job on the development!

**Comment by JonnyWong16** [comment]
Did you install using the `.qpkg`? It might be worth asking this on the QNAP forum thread.

**Comment by zhazell** [comment]
Yes, I just found the thread on QNAP and fixed it.

**Comment by zhazell** [comment]
http://forum.qnap.com/viewtopic.php?f=320&t=119855&start=15#p536157
