### ISSUE TITLE
Local PlexConnect User 404 error.

### ISSUE THREAD

**Issue by naq90** [Tautulli/Tautulli#584]
I have [PlexConnect ](https://github.com/iBaa/PlexConnect) set up so I can watch Plex on my Apple TV 2 on my local network. However PlexPy does not record any history for user when watching through PlexConnect. It does show if something is playing currently, however when trying to click the user I get a 404 error which reads: 

```
404 Not Found

Unexpected query string parameters: user

Traceback (most recent call last):
  File "/usr/local/share/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/share/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/share/plexpy/lib/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Unexpected query string parameters: user')
Powered by CherryPy 3.8.0
```

These are my logs:

Timestamp   Level   Message
2016-02-27 01:11:09 DEBUG   PlexPy ActivityProcessor :: History logging for user 'Local' is disabled.
2016-02-27 01:11:09 DEBUG   PlexPy ActivityHandler :: Session 105 has stopped.
2016-02-27 01:07:46 DEBUG   PlexPy ActivityHandler :: Session 105 has been paused.
2016-02-27 01:07:36 WARNING Unable to retrieve data for get_user_recently_watched.
2016-02-27 01:07:36 WARNING Unable to retrieve data for get_user_player_stats.
2016-02-27 01:07:36 WARNING Unable to retrieve data for get_user_watch_time_stats.
2016-02-27 01:07:36 WARNING PlexPy Users :: Unable to retrieve user from local database. Returning 'Local' user.
2016-02-27 01:07:36 INFO    PlexPy PlexTV :: Users list refreshed.
2016-02-27 01:07:35 INFO    PlexPy PlexTV :: Requesting users list refresh...
2016-02-27 01:07:35 WARNING PlexPy Users :: Unable to retrieve user from local database. Requesting user list refresh.
2016-02-27 00:44:54 DEBUG   PlexPy ActivityHandler :: Session 105 has started.
2016-02-27 00:42:38 DEBUG   PlexPy ActivityProcessor :: History logging for user 'Local' is disabled.

**Comment by JonnyWong16** [comment]
Have you tried logging out and back in to your Plex account on the Apple TV? Restarted the Apple TV?

**Comment by naq90** [comment]
For PlexConnect on the apple tv 3, there's an issue where you cannot sign in. It just searches for local servers on the network. I assume that this what plexpy is having a trouble with. Is there a way to work around this?

**Comment by JonnyWong16** [comment]
Does your stream show up in Plex Web's now playing page? If so which user?

**Comment by naq90** [comment]
Yes, it shows up in plex under my username (the one that the server is signed in as).
