### ISSUE TITLE
UnboundLocalError: local variable 'xml_parse' referenced before assignment

### ISSUE THREAD

**Issue by aaronchi** [Tautulli/Tautulli#6]
Just trying out some of the new features. Cool stuff.

Getting this error loading sync lists and when hitting refresh on the users list:

```
Traceback (most recent call last):
  File "lib/cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\plexpy\plexpy\webserve.py", line 934, in get_sync
    result = plex_tv.get_synced_items(machine_id=server_id['machine_identifier'], user_id=user_id)
  File "C:\plexpy\plexpy\plextv.py", line 292, in get_synced_items
    xml_head = xml_parse.getElementsByTagName('SyncList')
UnboundLocalError: local variable 'xml_parse' referenced before assignment
```

```
Traceback (most recent call last):
  File "lib/cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy\_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\plexpy\plexpy\webserve.py", line 907, in refresh_users_list
    result = plex_tv.get_full_users_list()
  File "C:\plexpy\plexpy\plextv.py", line 238, in get_full_users_list
    xml_head = xml_parse.getElementsByTagName('user')
UnboundLocalError: local variable 'xml_parse' referenced before assignment
```

**Comment by aaronchi** [comment]
Ah. I figured out that it was an access issue from the logs:

```
2015-07-03 22:21:06 WARNING Error parsing XML for Plex account details: must be string or read-only buffer, not None
2015-07-03 22:21:06 WARNING Failed to access user details. Status code 422
2015-07-03 22:21:06 WARNING Failed to access friends list. Status code 401
```

Adding my plex token solved the problem. You may want to handle these errors gracefully though.

**Comment by drzoidberg33** [comment]
Thanks for the feedback.

I'll make sure to add user feedback for anything that requires authentication.

**Comment by drzoidberg33** [comment]
I patched this slightly in commit https://github.com/drzoidberg33/plexpy/commit/b4f1bddc0233bba3ec9df6071ffe082092dbd51f. Not the final solution but at least won't cause those javascript errors now.
