### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by sltyler1** [Tautulli/Tautulli#601]
Not sure what happened. Getting the error listed below now.

`HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "C:\PlexPy\plexpy\logger.py", line 221, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\PlexPy\lib/cherrypy\process\servers.py", line 206, in _start_http_thread
    self.httpserver.start()
  File "C:\PlexPy\lib/cherrypy\wsgiserver\wsgiserver2.py", line 1955, in start
    raise socket.error(msg)
error: No socket could be created -- (('locahost', 8181): [Errno 11001] getaddrinfo failed)`

**Comment by JonnyWong16** [comment]
`localhost` is spelled wrong. You should be able to fix it in the `config.ini` file under `http_host`.

**Comment by sltyler1** [comment]
well that's embarrassing :/
not sure why it wasn't working before with 0.0.0.0 and just mistyped and didn't see it because the h is so close.
Thanks Jonny!
