### ISSUE TITLE
PlexPy unable to start when 'http_environment' option is set

### ISSUE THREAD

**Issue by AngryNoodlez** [Tautulli/Tautulli#641]
Hi Guys,

Just tried updating to the latest version a hit into a snag - but looking at the issues page it may be something related specifically to my environment.

The update went through as normal until it attempted to start the web server, upon which I received the following error;

```
2016-03-29 18:40:35 - ERROR :: MainThread : Uncaught exception: Traceback (most
recent call last):
File "plexpy.pyw", line 232, in <module>
    main()
  File "plexpy.pyw", line 191, in main
    webstart.initialize(web_config)
  File "C:\Apps\PlexPy\plexpy\webstart.py", line 49, in initialize
    'http_environment': options['http_environment'],
KeyError: 'http_environment'

Traceback (most recent call last):
  File "plexpy.pyw", line 232, in <module>
    main()
  File "plexpy.pyw", line 191, in main
    webstart.initialize(web_config)
  File "C:\Apps\PlexPy\plexpy\webstart.py", line 49, in initialize
    'http_environment': options['http_environment'],
KeyError: 'http_environment'
```

Looking at the code, it appears \plexpy\webstart.py is referencing some variable on line 322 in the config.ini file called '**http_environment**'. Mine is currently set to **Production** as shown below;

```
http_environment = production
```

My python experience is somewhat limited, but my first point of call was to see what would happen if I removed line 49 from webstart.py;

```
'http_environment': options['http_environment'],
```

This allowed it to start up normally, web server and all!

Not sure what this function does, and if it's something that's safe to leave out? (Seems OK!) But it would be a workaround I'd have to replace each update.

Any ideas what could be the cause? And also advise on what function the above option has within PlexPy?

I've included the OS / PlexPy details below;

> **Version:** 1.3.14
> **Branch:** master
> **Commit Hash:** 786a3742332bd9d1266b1c3d01e1432aea4f4143
> **OS:** Windows Server 2012 R2 Standard 64-bit
> **Python Version:** Python 2.7.9

Console log is short so hopefully it will be OK to post it here, let me know if I need to link it from elsewhere!

```
C:\Apps\PlexPy>C:\Python27\Python.exe plexpy.pyw
2016-03-29 18:54:19 - INFO :: MainThread : Checking to see if the database has all tables....
2016-03-29 18:54:19 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\Apps\PlexPy
2016-03-29 18:54:19 - DEBUG :: MainThread : Git output: 786a3742332bd9d1266b1c3d01e1432aea4f4143
2016-03-29 18:54:19 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\Apps\PlexPy
2016-03-29 18:54:19 - DEBUG :: MainThread : Git output: master
2016-03-29 18:54:19 - INFO :: MainThread : Retrieving latest version information from GitHub
2016-03-29 18:54:19 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
2016-03-29 18:54:21 - DEBUG :: MainThread : Latest version is 786a3742332bd9d1266b1c3d01e1432aea4f4143
2016-03-29 18:54:21 - INFO :: MainThread : PlexPy is up to date
2016-03-29 18:54:21 - INFO :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2016-03-29 18:54:21 - INFO :: MainThread : Writing configuration to file
2016-03-29 18:54:21 - INFO :: MainThread : Writing configuration to file
2016-03-29 18:54:21 - INFO :: MainThread : PlexPy PlexTV :: Server URL retrieved.
2016-03-29 18:54:21 - INFO :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2016-03-29 18:54:21 - INFO :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2016-03-29 18:54:22 - INFO :: MainThread : PlexPy PlexTV :: Users list refreshed.
2016-03-29 18:54:22 - INFO :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2016-03-29 18:54:23 - INFO :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2016-03-29 18:54:23 - ERROR :: MainThread : Uncaught exception: Traceback (mostrecent call last):
  File "plexpy.pyw", line 232, in <module>
    main()
  File "plexpy.pyw", line 191, in main
    webstart.initialize(web_config)
  File "C:\Apps\PlexPy\plexpy\webstart.py", line 49, in initialize
    'http_environment': options['http_environment'],
KeyError: 'http_environment'

Traceback (most recent call last):
  File "plexpy.pyw", line 232, in <module>
    main()
  File "plexpy.pyw", line 191, in main
    webstart.initialize(web_config)
  File "C:\Apps\PlexPy\plexpy\webstart.py", line 49, in initialize
    'http_environment': options['http_environment'],
KeyError: 'http_environment'
```

Thanks for building such a fantastic solution! Great work, and I appreciate any guidance the community may be able to provide!

**Comment by JonnyWong16** [comment]
You're trying to start PlexPy with a modified `PlexPy.pyw` file.

v1.3.12 made changes to the `PlexPy.py` file so you're trying to run it with an out of date file. Use [this method](https://github.com/drzoidberg33/plexpy/wiki/Install-as-a-daemon#windows) instead to start PlexPy without the command prompt open.

Or start manually with `pythonw` instead.

```
C:\Python27\Pythonw.exe PlexPy.py
```

---

Discussion on what the `http_environment` does: #612 

P.S. This is a great example of what a proper issue report should look like. Thanks for providing all the info. :thumbsup:

**Comment by AngryNoodlez** [comment]
Perfect!

I have it run by scheduled task, have changed it to launch pythonw.exe directly and input the plexpy.py file - Works like a charm!

The new environment feature looks awesome too! Can't wait to play with it.

Thanks Jonny!

P.S - Only have to read the guidelines! :+1:
