### ISSUE TITLE
Plexpy on archlinux from AUR failed to start

### ISSUE THREAD

**Issue by KennyVB** [Tautulli/Tautulli#675]
Hello
i just installed it and get this error when trying to start it
archlinux 4.4.5-1-ARCH

```
  python2 PlexPy.py 
Traceback (most recent call last):
  File "PlexPy.py", line 31, in <module>
    from plexpy import webstart, logger, web_socket
  File "/opt/plexpy/plexpy/__init__.py", line 52, in <module>
    SCHED = BackgroundScheduler()
  File "lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "lib/tzlocal/unix.py", line 100, in _get_localzone
    return pytz.tzfile.build_tzinfo('local', tzfile)
  File "lib/pytz/tzfile.py", line 30, in build_tzinfo
    typecnt, charcnt) =  unpack(head_fmt, fp.read(head_size))
struct.error: unpack requires a string argument of length 44
```

**Comment by ghost** [comment]
Did you find a solution to this problem? I am in the same boat right now and nothing seems to work.

**Comment by GNOMES** [comment]
This was closed? Installing from both AUR packages, or downloading directly from Git and using install guide, I get the same error: `File "PlexPy.py", line 35, in <module>
    import plexpy
  File "/opt/plexpy/plexpy/__init__.py", line 58, in <module>
    SCHED = BackgroundScheduler()
  File "lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "lib/tzlocal/unix.py", line 100, in _get_localzone
    return pytz.tzfile.build_tzinfo('local', tzfile)
  File "lib/pytz/tzfile.py", line 30, in build_tzinfo
    typecnt, charcnt) =  unpack(head_fmt, fp.read(head_size))
struct.error: unpack requires a string argument of length 44
`

**Comment by ghost** [comment]
Hey, so I figured out the issue on my end. For some reason I had to regenerate the timezone file and all that. This [link](https://wiki.archlinux.org/index.php/time#Time_zone) helped, just follow the timedatectl commands.

**Comment by GNOMES** [comment]
Talked to Dev, they mentioned the same thing. During normal Arch install process you of course have to define your timezone. On my install plexpy would only detect these settings if ran by su or sudo. After re configuring timezone, and adjusting permissions of directly where file is located it worked.
