### ISSUE TITLE
Cannot refresh user list or retrieve sync data.

### ISSUE THREAD

**Issue by JonnyWong16** [Tautulli/Tautulli#72]
PlexPy (v1.1.1) is running in a FreeNAS (9.3) jail (separate from PMS jail). Warnings show up whenever the user list is refreshed (automatically or manually), and when accessing the "Synced Items" page.

PlexPy Logs:

```
2015-08-15 18:10:39 WARNING Unable to retrieve sync data for user.
2015-08-15 18:10:39 WARNING Error parsing XML for Plex sync lists: must be string or read-only buffer, not None`
2015-08-15 18:10:39 WARNING Failed to access uri endpoint /servers/****/sync_lists with error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
2015-08-15 18:04:45 WARNING Unable to refresh users list.
2015-08-15 18:04:45 WARNING Error parsing XML for Plex account details: must be string or read-only buffer, not None
2015-08-15 18:04:45 WARNING Failed to access uri endpoint /users/account with error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
2015-08-15 18:04:45 WARNING Failed to access uri endpoint /api/users with error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

**Comment by drzoidberg33** [comment]
It may be the FreeNAS has an outdated CA store. You could try disabling SSL verification checking by following these steps:
- Make sure PlexPy is configured and running
- Quit PlexPy. Make sure it quitted! You need to stop the service, otherwise the changes you make will disappear.
- Open config.ini in your favourite text editor
- Set verify_cert_ssl to 0. The key should under the [Advanced] section, and by default, it should mention the value 1
  *Save the file.
- Start PlexPy again.

This may solve the problem if your Python version is compatible.

**Comment by JonnyWong16** [comment]
I changed verify_cert_ssl to 0, but PlexPy wouldn't start due to an error with the user list database. Since I never had a proper user list refresh from the start, I never got the profile pictures, and it was trying to pull custom profile pictures.

So I reverted to version v1.0.1, before custom profile pictures were implemented, and started up PlexPy. The user list (and Synced Items) refreshed and grabbed all the profile pictures. I then updated to v1.1.2, and everything seems to be working so far.

Here is the error log that I got before reverting to an older version:

```
16-Aug-2015 10:26:24 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "PlexPy.py", line 220, in <module>
    main()
  File "PlexPy.py", line 155, in main
    plexpy.initialize(config_file)
  File "/usr/local/share/plexpy/plexpy/__init__.py", line 168, in initialize
    plextv.refresh_users()
  File "/usr/local/share/plexpy/plexpy/plextv.py", line 45, in refresh_users
    if not avatar_urls[0]['custom_avatar_url'] or \
IndexError: list index out of range
```

Now, is there a way to fix SSL in FreeNAS? I might have to ask somewhere else.

**Comment by drzoidberg33** [comment]
Great, glad you came right.

You should be able to fix the SSL in FreeNAS by importing the correct system CAs. I'm not all that clued up on FreeNAS/FreeBSD - asking on their forum will probably be the best bet.

**Comment by JonnyWong16** [comment]
I did a bit of digging and found [this](https://nixbsd.wordpress.com/2015/01/02/freebsd-ssl-certificate_verify_failed/) FreeBSD solution. The ca_root_nss package just needs to be updated.

`pkg install security/ca_root_nss`

Setting verify_cert_ssl to 1 works again. :)
