### ISSUE TITLE
KeyError: 'http_environment' Unable to start

### ISSUE THREAD

**Issue by ajlaventure** [Tautulli/Tautulli#725]
**Version:**
1.4.3

**Branch:**
cfc7d529e1917a88fa5d9038f2f5871c5a60fb4b

**Commit hash:**
2016-05-23 10:38:11 - DEBUG   :: MainThread : Git output: cfc7d529e1917a88fa5d9038f2f5871c5a60fb4b

**Operating system:**
Win 10

**Python version:**
2.7.9

**What you did?**
updated to latest branch

**What happened?**
Service couldn't start due to exception below in webstart.py options.

**What you expected?**
The server to start

**How can we reproduce your issue?**
I fixed by going in to `PlexPy/plexpy/webstart.py` and commenting out the option where the error occured

```
 options_dict = {
        'server.socket_port': options['http_port'],
        'server.socket_host': options['http_host'],
       # 'environment': options['http_environment'],
        'server.thread_pool': 10,
        'tools.encode.on': True,
        'tools.encode.encoding': 'utf-8',
        'tools.decode.on': True
    }
```

**What are your (relevant) settings?**

**Link to logs:**

```
2016-05-23 10:38:12 - DEBUG   :: MainThread : Latest version is cfc7d529e1917a88fa5d9038f2f5871c5a60fb4b
2016-05-23 10:38:12 - INFO    :: MainThread : PlexPy is up to date
2016-05-23 10:38:12 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2016-05-23 10:38:12 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2016-05-23 10:38:13 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2016-05-23 10:38:13 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2016-05-23 10:38:13 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2016-05-23 10:38:13 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2016-05-23 10:38:14 - INFO    :: MainThread : PlexPy PlexTV :: Users list refreshed.
2016-05-23 10:38:14 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting libraries list refresh...
2016-05-23 10:38:14 - INFO    :: MainThread : PlexPy Pmsconnect :: Libraries list refreshed.
2016-05-23 10:38:14 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\<user>\Documents\PlexPy\PlexPy.pyw", line 232, in <module>
    main()
  File "C:\Users\<user>\Documents\PlexPy\PlexPy.pyw", line 191, in main
    webstart.initialize(web_config)
  File "C:\Users\<user>\Documents\PlexPy\plexpy\webstart.py", line 49, in initialize
    'environment': options['http_environment'],
KeyError: 'http_environment'
```

**Comment by JonnyWong16** [comment]
https://github.com/drzoidberg33/plexpy/issues/641#issuecomment-203030097
