### ISSUE TITLE
June 26 dev update: TypeError

### ISSUE THREAD

**Issue by mbnn** [Tautulli/Tautulli#765]
Since latest dev update (june 26, 2016) it wont start anymore on Ubuntu 16.04, I see this in the logs:

2016-06-26 12:14:44 - INFO    :: MainThread : Checking to see if the database has all tables....
2016-06-26 12:14:44 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
2016-06-26 12:14:44 - DEBUG   :: MainThread : Git output: ee7ca68f87b022e2035821781fe82f1f1935427f
2016-06-26 12:14:44 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
2016-06-26 12:14:44 - DEBUG   :: MainThread : Git output: dev
2016-06-26 12:14:44 - INFO    :: MainThread : Retrieving latest version information from GitHub
2016-06-26 12:14:44 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/dev
2016-06-26 12:14:45 - DEBUG   :: MainThread : Latest version is ee7ca68f87b022e2035821781fe82f1f1935427f
2016-06-26 12:14:45 - INFO    :: MainThread : PlexPy is up to date
2016-06-26 12:14:45 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2016-06-26 12:14:45 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2016-06-26 12:14:45 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "PlexPy.py", line 247, in <module>
    main()
  File "PlexPy.py", line 173, in main
    plexpy.initialize(config_file)
  File "/opt/plexpy/plexpy/**init**.py", line 189, in initialize
    plextv.get_real_pms_url()
  File "/opt/plexpy/plexpy/plextv.py", line 115, in get_real_pms_url
    connections = [c for c in result if c['local'] == '0' and 'plex.direct' in c['uri']]
TypeError: string indices must be integers, not str

 Any idea? :)

**Comment by mbnn** [comment]
FYI This seems to happen only when SSL is enabled.

**Comment by Collisionc** [comment]
Can confirm, only happens with the config.ini setting:
pms_ssl = 1

Setting that to 0 allows plexpy to run.

**Comment by Hellowlol** [comment]
Result is prob a empty list. Should use .get

**Comment by JonnyWong16** [comment]
It's because I made a typo... Sorry
