### ISSUE TITLE
Latest dev broken

### ISSUE THREAD

**Issue by pax0707** [Tautulli/Tautulli#768]
Tried reset, reverted to master.

```
D:\Plex\PlexPy>python plexpy.py
Traceback (most recent call last):
  File "plexpy.py", line 35, in <module>
    import plexpy
  File "D:\Plex\PlexPy\plexpy\__init__.py", line 34, in <module>
    import activity_pinger
  File "D:\Plex\PlexPy\plexpy\activity_pinger.py", line 20, in <module>
    import activity_processor
  File "D:\Plex\PlexPy\plexpy\activity_processor.py", line 21, in <module>
    import database
  File "D:\Plex\PlexPy\plexpy\database.py", line 24, in <module>
    import logger
  File "D:\Plex\PlexPy\plexpy\logger.py", line 30, in <module>
    import helpers
  File "D:\Plex\PlexPy\plexpy\helpers.py", line 19, in <module>
    import geoip2.database, geoip2.errors
  File "lib/geoip2\database.py", line 9, in <module>
    import maxminddb
  File "lib/maxminddb\__init__.py", line 4, in <module>
    import maxminddb.reader
  File "lib/maxminddb\reader.py", line 18, in <module>
    from maxminddb.compat import byte_from_int, int_from_byte, compat_ip_address

  File "lib/maxminddb\compat.py", line 3, in <module>
    import ipaddress
ImportError: No module named ipaddress
```

```
Git Branch: master
Git Commit Hash:    d9474cdcc5e72ff311569a234e3abe7dec06d9a2
Configuration File: D:\Plex\PlexPy\config.ini
Database File:  D:\Plex\PlexPy\plexpy.db
Log File:   D:\Plex\PlexPy\logs\plexpy.log
Backup Directory:   D:\Plex\PlexPy\backups
Cache Directory:    D:\Plex\PlexPy\cache
Platform:   Windows 10
Python Version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
```

**Comment by JonnyWong16** [comment]
Try again now.

**Comment by pax0707** [comment]
Working.

**Comment by debostic** [comment]
I'm having this problem and I'm not on dev.

**Comment by JonnyWong16** [comment]
@debostic Update again to v1.4.10.

```
git fetch origin
git pull
```
