### ISSUE TITLE
Pushover Notifications Settings Error

### ISSUE THREAD

**Issue by gvnmccld** [Tautulli/Tautulli#781]
Version: 1.4.7
Branch: master
Commit hash: 26ac539bc46a72fc79d184da0a4e24b3858e5db1
OS: Ubuntu Xenial (Linux 4.4.0-28-generic)
Python Version: 2.7.11+

In adding api keys for pushover notifications, the api keys are saved to the config file and afterwards the modal for modifying the settings throws a 500 error.  No specific error is given on screen (besides 500) or in the logs (nothing noted in the logs).  I checked the config file and the api keys are saved in there, if i remove them from the config the modal works as expected.  Toggling the bell icon has no affect.

I'm not sure if this is new to 1.4.7 or previously existed as I didn't try setting it up prior to this version.

**Comment by JonnyWong16** [comment]
Screenshot? Can you see if there are errors in your browser console. (Press F12 in your browser)

**Comment by gvnmccld** [comment]
![pushover](https://cloud.githubusercontent.com/assets/57923/16888275/d8c6efb4-4a93-11e6-9b2c-bd619fc25552.png)
![pushover-console](https://cloud.githubusercontent.com/assets/57923/16888276/d8e065e8-4a93-11e6-80fb-b99dfab2a5c9.png)
![pushover-console2](https://cloud.githubusercontent.com/assets/57923/16888277/d8e745e8-4a93-11e6-9c01-8ebb25bc0ab3.png)

**Comment by JonnyWong16** [comment]
And your logs?

**Comment by gvnmccld** [comment]
Nothing relevant at all, besides normal startup logs this is the only thing that pops up:

```
2016-07-15 15:06:23 WARNING PlexPy PlexTV :: Unable to parse XML for get_plexpass_status: 'NoneType' object has no attribute 'getElementsByTagName'.
2016-07-15 15:06:23 WARNING Failed to access uri endpoint /users/account with error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by JonnyWong16** [comment]
Post everything please.

**Comment by gvnmccld** [comment]
[plexpy.txt](https://github.com/drzoidberg33/plexpy/files/366928/plexpy.txt)

**Comment by JonnyWong16** [comment]
Can you start PlexPy in dev mode please?

```
python PlexPy.py --dev
```

It should now show the error when opening the Pushover modal popup.

(Note: To shut down PlexPy in dev mode you need to end the process in the terminal with Ctrl+C)

**Comment by gvnmccld** [comment]
```
Traceback (most recent call last):
  File "/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/plexpy/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/plexpy/plexpy/webserve.py", line 2840, in get_notification_agent_config
    config = notifiers.get_notification_agent_config(agent_id=agent_id)
  File "/plexpy/plexpy/notifiers.py", line 507, in get_notification_agent_config
    return pushover.return_config_options()
  File "/plexpy/plexpy/notifiers.py", line 1361, in return_config_options
    'select_options': self.get_sounds()
  File "/plexpy/plexpy/notifiers.py", line 1317, in get_sounds
    http_handler.request("GET", "/1/sounds.json?token=" + self.apitoken)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by JonnyWong16** [comment]
Can you even access https://api.pushover.net from your computer? Google "Ubuntu certificate verify failed".

**Comment by gvnmccld** [comment]
I get a 301, moved permanently with that url, following the redirect url I can load the page:

```
curl -i https://pushover.net/api
HTTP/1.1 200 OK
Date: Sat, 16 Jul 2016 01:20:34 GMT
```

FWIW this is running in a docker container and I tested in said container.  Other containers running on the same box can use pushover to send notifications.

**Comment by JonnyWong16** [comment]
Well, this isn't a PlexPy issue.

**Comment by gvnmccld** [comment]
Alrighty.
