### ISSUE TITLE
Trouble importing Plexwatch DB.

### ISSUE THREAD

**Issue by mochflix** [Tautulli/Tautulli#822]
Hi,

I'm getting ready to make the move from plexwatch(web) to Plexpy, but for some reason I keep getting an error when trying to import my Plexwatch database. 

The Logs state the following:

2016-08-22 20:20:46 - DEBUG   :: Thread-16 : PlexPy Importer :: PlexWatch data import in progress...
2016-08-22 20:20:46 - DEBUG   :: Thread-16 : PlexPy Importer :: Disabling monitoring while import in progress.
2016-08-22 20:20:46 - INFO    :: Thread-16 : PlexPy PlexTV :: Requesting users list refresh...
2016-08-22 20:20:48 - INFO    :: Thread-16 : PlexPy PlexTV :: Users list refreshed.
2016-08-22 20:20:48 - ERROR   :: Thread-16 : Uncaught exception: Traceback (most recent call last):
  File "C:\PlexPy\plexpy\logger.py", line 270, in new_run
    old_run(_args, *_kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\PlexPy\plexpy\plexwatch_import.py", line 408, in import_from_plexwatch
    import_ignore_interval=import_ignore_interval)
  File "C:\PlexPy\plexpy\activity_processor.py", line 301, in write_session_history
    session['transcode_decision']]
KeyError: 'transcode_decision'

If Needed I can supply a link to my Database in my google drive

Thanks very much in advance for any help.

**Comment by Hellowlol** [comment]
Hi. Please use the search function

**Comment by mochflix** [comment]
You're right! just found the post with the 1.4.10/1.4.08 bug.. My bad.. sorry
