### ISSUE TITLE
ParseError: Invalid Line

### ISSUE THREAD

**Issue by mmenanno** [Tautulli/Tautulli#823]
**Version:**
PlexPy v1.4.10

**Branch:**
master

**Commit hash:**
2a701a6

**Operating system:**
Mac OS X 10.11.6

**Python version:**
2.7.11

**What you did?**
Try to start PlexPy.

**What happened?**
Getting an error.

**What you expected?**
Application to start.

**How can we reproduce your issue?**
Start PlexPy
Receive error in terminal.

**Link to logs:**

```
2016-08-23 16:16:25 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "PlexPy.py", line 247, in <module>
    main()
  File "PlexPy.py", line 173, in main
    plexpy.initialize(config_file)
  File "/Applications/PlexPy/plexpy/__init__.py", line 96, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/PlexPy/plexpy/config.py", line 633, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "310".

Traceback (most recent call last):
  File "PlexPy.py", line 247, in <module>
    main()
  File "PlexPy.py", line 173, in main
    plexpy.initialize(config_file)
  File "/Applications/PlexPy/plexpy/__init__.py", line 96, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/PlexPy/plexpy/config.py", line 633, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
configobj.ParseError: Invalid line at line "310".
```

**Comment by JonnyWong16** [comment]
Your config file got corrupted. Or you tried to change something manually in the file and broke it. Restore a backup `config.ini` file from the `backup` folder.

**Comment by mmenanno** [comment]
That worked! Thanks!
