### ISSUE TITLE
Error when importing from PlexWatch DB

### ISSUE THREAD

**Issue by BSBarrows** [Tautulli/Tautulli#829]
Hi all,

New to PlexPy and love it so far, just looking to import my PlexWatch/PlexWatchWeb DB into PlexPy and keep running into an issue. I get this in PlexPy:

`Uncaught exception: Traceback (most recent call last):
    File "C:\Program Files (x86)\PlexPy\plexpy\logger.py", line 270, in new_run 
        old_run(*args, **kwargs) 
    File "C:\Python27\lib\threading.py", line 754, in run 
        self.__target(*self.__args, **self.__kwargs) 
    File "C:\Program Files (x86)\PlexPy\plexpy\plexwatch_import.py", line 408, in import_from_plexwatch 
        import_ignore_interval=import_ignore_interval) 
    File "C:\Program Files (x86)\PlexPy\plexpy\activity_processor.py", line 301, in write_session_history 
        session['transcode_decision']] 
KeyError: 'transcode_decision'`

Any thoughts? I can provide the PlexWatch DB as well if that helps...

Thank you!

-BSBarrows

Version: 1.4.10

Branch: master

Commit hash:    2a701a6dfea6ef4abda0c6db5f23f59d2a251a35

Operating system: Windows 7

Python version: 2.7.12

Link to logs: 
https://dl.dropboxusercontent.com/u/144146/plexpy.log 

https://dl.dropboxusercontent.com/u/144146/plexWatch.db

**Comment by JonnyWong16** [comment]
Please search first #815.
