### ISSUE TITLE
Attempting to view info on deleted media item gives 500

### ISSUE THREAD

**Issue by Arcanemagus** [Tautulli/Tautulli#873]
**Version:**
v1.4.14

**Branch:**
`master`

**Commit hash:**
86a9230da8a9ab1af18eacb07a9fd7086437305c (Also found with 1a2e205)

**Operating system:**
FreeBSD 10.3-STABLE

**Python version:**
2.7.12 (default, Jul 26 2016, 01:23:30) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]

**What you did?**
When updating the source media for a particular movie Plex decided to delete/recreate it as it sometimes does. I went to PlexPy to attempt to load up the info page for the deleted `rating_key` to check if there were any history items related to it, but ran into a 500 server error.

**What happened?**
Starting PlexPy with `--dev` gives the following trace:

``` pytb
Traceback (most recent call last):
  File "/usr/local/share/plexpy/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/share/plexpy/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/share/plexpy/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/share/plexpy/plexpy/webserve.py", line 3259, in info
    metadata['poster_url'] = poster_url
TypeError: 'NoneType' object does not support item assignment
```

Interestingly if instead of loading `...?rating_key=341199` directly I load `...?souce=history&rating_key=341199` (from history search results) the page loads just fine.

**What you expected?**
No crash, the page for the deleted media item to load allowing the metadata to be updated to the new `rating_key`

**How can we reproduce your issue?**
Possibly by having an item in your Plex library, removing it from Plex, and adding it again so Plex creates a new item, then attempting to load the info page in PlexPy.

**What are your (relevant) settings?**
N/A

**Link to logs:**
No entries in the logs.

**Comment by Arcanemagus** [comment]
Looks like this was fixed by 4e043109bf70a481024964184e53577a81b5f059, thanks!
