### ISSUE TITLE
Installation Broken on Centos 6.7

### ISSUE THREAD

**Issue by dshareiff** [Tautulli/Tautulli#887]
Centos 6.7 install, Plex 2.8.1 

[root@plexsvr02 plexpy]# python PlexPy.py
Traceback (most recent call last):
  File "PlexPy.py", line 35, in <module>
    import plexpy
  File "/opt/plexpy/plexpy/**init**.py", line 34, in <module>
    import activity_pinger
  File "/opt/plexpy/plexpy/activity_pinger.py", line 20, in <module>
    import activity_processor
  File "/opt/plexpy/plexpy/activity_processor.py", line 21, in <module>
    import database
  File "/opt/plexpy/plexpy/database.py", line 24, in <module>
    import logger
  File "/opt/plexpy/plexpy/logger.py", line 30, in <module>
    import helpers
  File "/opt/plexpy/plexpy/helpers.py", line 41, in <module>
    from plexpy.api2 import API2
  File "/opt/plexpy/plexpy/api2.py", line 36, in <module>
    import plextv
  File "/opt/plexpy/plexpy/plextv.py", line 29, in <module>
    import users
  File "/opt/plexpy/plexpy/users.py", line 22, in <module>
    import datatables
  File "/opt/plexpy/plexpy/datatables.py", line 105
    result = [{k: helpers.sanitize(v) if isinstance(v, basestring) else v for k, v in row.iteritems()}
                                                                            ^
SyntaxError: invalid syntax

**Version:**

**Branch:**

**Commit hash:**

**Operating system:**

**Python version:**

**What you did?**

**What happened?**

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
The very very first answer in the FAQ.
