### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by elRadix** [Tautulli/Tautulli#9]
Hi,

When running plexy through python, everything works good but running as deamon I receive an error, I followed the instruction very good

Running as deamon

``` javascript
root@debian:/# service plexpy start
[warn] Removing stale /var/run/plexpy/plexpy.pid ... (warning).
[....] Starting PlexPy:Traceback (most recent call last):
  File "PlexPy.py", line 220, in <module>
    main()
  File "PlexPy.py", line 155, in main
    plexpy.initialize(config_file)
  File "/opt/plexpy/plexpy/__init__.py", line 167, in initialize
    plextv.refresh_users()
  File "/opt/plexpy/plexpy/plextv.py", line 40, in refresh_users
    pw_db.upsert('plexpy_users', new_value_dict, control_value_dict)
  File "/opt/plexpy/plexpy/db.py", line 111, in upsert
    self.action(update_query, valueDict.values() + keyDict.values())
  File "/opt/plexpy/plexpy/db.py", line 70, in action
    sqlResult = c.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
 failed!
```

Run as python command

``` javascript
root@debian:/opt/plexpy# python PlexPy.py 
06-Jul-2015 11:08:13 - INFO :: MainThread : Checking to see if the database has all tables....
06-Jul-2015 11:08:13 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
06-Jul-2015 11:08:13 - DEBUG :: MainThread : Git output: 7a5cad1a31cb0e7a98af45b449b6219527a9cd72
06-Jul-2015 11:08:13 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /opt/plexpy
06-Jul-2015 11:08:13 - DEBUG :: MainThread : Git output: master
06-Jul-2015 11:08:13 - INFO :: MainThread : Retrieving latest version information from GitHub
06-Jul-2015 11:08:13 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/drzoidberg33/plexpy/commits/master
06-Jul-2015 11:08:14 - DEBUG :: MainThread : Latest version is 7a5cad1a31cb0e7a98af45b449b6219527a9cd72
06-Jul-2015 11:08:14 - INFO :: MainThread : PlexPy is up to date
06-Jul-2015 11:08:14 - INFO :: MainThread : Requesting users list refresh...
06-Jul-2015 11:08:16 - INFO :: MainThread : Users list refreshed.
06-Jul-2015 11:08:16 - INFO :: MainThread : Starting PlexPy web server on http://0.0.0.0:8181/
06-Jul-2015 11:08:16 - INFO :: MainThread : Web server authentication is enabled, username is 'admin'
06-Jul-2015 11:08:17 - INFO :: MainThread : Scheduled background task: Check GitHub for updates
06-Jul-2015 11:08:17 - INFO :: MainThread : Scheduled background task: Check for active sessions
06-Jul-2015 11:08:17 - INFO :: MainThread : Scheduled background task: Refresh users list
```

what's the issue here ?

**Comment by drzoidberg33** [comment]
This is the issue:

sqlite3.OperationalError: attempt to write a readonly database

The init script is running as a different user (not root) which it would appear doesn't have write access to your plexWatch database.

Either give write access on your plexWatch db to the user in the init script or make your plexWatch db writeable to all.

I'm working on completely removing the need for plexWatch but that may take a while still to become a stable feature.

**Comment by elRadix** [comment]
how can I change that in the init script ?
what specifically ?

---

update its fixed now
as you said updated the init.ubuntu script by adding this line on the top
HP_USER=root

**Comment by drzoidberg33** [comment]
You shouldn't be editing that script directly.

You just need to add the line HP_USER={your_username} to /etc/default/plexpy

I also wouldn't advise you to run this software as root, especially that it's still so early in development. You're essentially giving the app full access to the system and anything could go wrong.

Create a new user to run PlexPy as, see the instructions in the init script. Then give this user write access to the plexWatch db.
