### ISSUE TITLE
PlexPY install on new server, wont  launch with backed up DB

### ISSUE THREAD

**Issue by ScouseTS** [Tautulli/Tautulli#931]
**Version:**  VERSION 1.4.16

**Branch:** N/A

**Commit hash:**

**Operating system:** Windows Server 2012 R2

**Python version:** 7.2.0

**What you did?** Old server drive had gone into predicted failure,, copied across the db file to a different drive in server and then re-installed PlexPY on new drive once it had been replaced and OS rebuilt. PlexPY will not launch when using the old database.

**What happened?** When I went through inital PlexPY config I closed the software and replaced the created DB file with my backed up one, executed to launch it again and it just closes instantly.

**What you expected?** Was hoping for it to just start up as usual using the old DB

**Comment by Hellowlol** [comment]
Anything in the logs? Tried starting it manually. Should be a trace back there.

**Comment by ScouseTS** [comment]
```
016-12-21 15:18:23 - INFO    :: MainThread : Checking to see if the database has all tables....
2016-12-21 15:18:23 - ERROR   :: MainThread : Can't connect to the database: file is encrypted or is not a database
2016-12-21 15:18:23 - INFO    :: MainThread : Retrieving latest version information from GitHub
2016-12-21 15:18:23 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/JonnyWong16/plexpy/commits/master
2016-12-21 15:18:25 - DEBUG   :: MainThread : Latest version is 3742f33d08feb6fb15e74af6318185230205006f
2016-12-21 15:18:25 - INFO    :: MainThread : PlexPy is up to date
2016-12-21 15:18:25 - INFO    :: MainThread : PlexPy PlexTV :: Requesting URLs for server...
2016-12-21 15:18:26 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2016-12-21 15:18:26 - INFO    :: MainThread : PlexPy Config :: Writing configuration to file
2016-12-21 15:18:26 - INFO    :: MainThread : PlexPy PlexTV :: Using user-defined URL.
2016-12-21 15:18:26 - INFO    :: MainThread : PlexPy Pmsconnect :: Requesting name from server...
2016-12-21 15:18:26 - INFO    :: MainThread : PlexPy PlexTV :: Requesting users list refresh...
2016-12-21 15:18:28 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\plexpy-2\PlexPy.py", line 260, in <module>
    main()
  File "C:\Users\Administrator\Documents\plexpy-2\PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
```

**Comment by ScouseTS** [comment]
Fixed, I followed the FAQ entry for that :)
