### ISSUE TITLE
PlexPy won't start after reboot

### ISSUE THREAD

**Issue by timmyk0** [Tautulli/Tautulli#932]
**Version:** Latest, I believe. Can't check as it won't run.

**Branch:** Master

**Commit hash:**

**Operating system:** Windows Server 2012 R2

**Python version:** 2.7.10

**What you did?** Rebooted server

**What happened?** PlexPy will not load via web browser, checked logs and saw errors. It was working fine earlier in the day.

**What you expected?** Reboot like usual and PlexPy starts up like it always does automatically. 

**How can we reproduce your issue?**
Not sure, it usually works fine after a reboot. 

**What are your (relevant) settings?**

**Link to logs:** https://gist.github.com/timmyk0/39563d5000b291ed063eea900b7d3b86

**When trying to run from the command prompt this is the result I get:**
C:\Python27>python.exe C:\PlexPy\PlexPy.py
2016-12-22 12:04:17 - ERROR :: MainThread : Uncaught exception: Traceback (most
recent call last):
  File "C:\PlexPy\PlexPy.py", line 260, in <module>
    main()
  File "C:\PlexPy\PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "C:\PlexPy\plexpy\__init__.py", line 96, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "C:\PlexPy\plexpy\config.py", line 637, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "C:\PlexPy\lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "C:\PlexPy\lib/configobj.py", line 1332, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 593.

Traceback (most recent call last):
  File "C:\PlexPy\PlexPy.py", line 260, in <module>
    main()
  File "C:\PlexPy\PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "C:\PlexPy\plexpy\__init__.py", line 96, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "C:\PlexPy\plexpy\config.py", line 637, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "C:\PlexPy\lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "C:\PlexPy\lib/configobj.py", line 1332, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 593.

If there's any further info you need please let me know. Thanks for your help!

**Comment by JonnyWong16** [comment]
Your config file got corrupted. Either restore a backup configuration file or delete it and reconfigure everything.

**Comment by timmyk0** [comment]
@JonnyWong16, thank you... I couldn't tell what the issue was from the logs but I restored from an automatic backup Plexpy makes from only 10 minutes or so before the reboot and that took care of it. Everything is working fine now. Thanks for the fast response!
