### ISSUE TITLE
PlexPy won't start

### ISSUE THREAD

**Issue by knocc** [Tautulli/Tautulli#960]
Hi guys! When i double click "PlexPy.py", the command window just flashes for a second and then closes. So i tried starting from command prompt and the follwing errors appeared: 

```
2017-02-05 17:43:30 - INFO :: MainThread : Checking to see if the database has all tables....
2017-02-05 17:43:30 - ERROR :: MainThread : Can't connect to the database: unable to open database file
2017-02-05 17:43:30 - DEBUG :: MainThread : Generating UUID...
2017-02-05 17:43:30 - INFO :: MainThread : PlexPy Config :: Writing configuration to file
2017-02-05 17:43:30 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\Mário\Documents\PlexPy\PlexPy.py", line 260, in <module>
    main()
  File "C:\Users\Mário\Documents\PlexPy\PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "C:\Users\Mário\Documents\PlexPy\plexpy\__init__.py", line 158, in initialize
    CONFIG.write()
  File "C:\Users\Mário\Documents\PlexPy\plexpy\config.py", line 709, in write
    new_config.write()
  File "C:\Users\Mário\Documents\PlexPy\lib/configobj.py", line 2059, in write
    out.extend(self.write(section=this_entry))
  File "C:\Users\Mário\Documents\PlexPy\lib/configobj.py", line 2065, in write
    comment))
  File "C:\Users\Mário\Documents\PlexPy\lib/configobj.py", line 1982, in _write_line
    self._decode_element(comment))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 10: ordinal not in range(128)

Traceback (most recent call last):
  File "C:\Users\Mário\Documents\PlexPy\PlexPy.py", line 260, in <module>
    main()
  File "C:\Users\Mário\Documents\PlexPy\PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "C:\Users\Mário\Documents\PlexPy\plexpy\__init__.py", line 158, in initialize
    CONFIG.write()
  File "C:\Users\Mário\Documents\PlexPy\plexpy\config.py", line 709, in write
    new_config.write()
  File "C:\Users\Mário\Documents\PlexPy\lib/configobj.py", line 2059, in write
    out.extend(self.write(section=this_entry))
  File "C:\Users\Mário\Documents\PlexPy\lib/configobj.py", line 2065, in write
    comment))
  File "C:\Users\Mário\Documents\PlexPy\lib/configobj.py", line 1982, in _write_line
    self._decode_element(comment))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 10: ordinal not in range(128)
```

I don't know if it was something I did wrong during installation. Thanks in advance!

**Comment by JonnyWong16** [comment]
Something wrong with your config file.

Or it might be the `á` in your name.

**Comment by knocc** [comment]
You were right. It was the "á". Changed the directory and it worked!
