### ISSUE TITLE
There was an error communicating with your Plex Server.

### ISSUE THREAD

**Issue by magiasegura** [Tautulli/Tautulli#978]
PLEXPY CONFIGURATION:
VERSION 1.4.16
Git Branch:	v2
Git Commit Hash:	cea851d38ea8dfe432cf7268cc84d8c6fd79cb3d
Platform:	Linux 4.4.0-64-generic
Python Version:	2.7.12

Error Log:
```
Unable to retrieve data for get_activity: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
Traceback (most recent call last): 
    File "/opt/plexpy/plexpy/webserve.py", line 4227, in get_activity 
        result = pms_connect.get_current_activity() 
    File "/opt/plexpy/plexpy/pmsconnect.py", line 1140, in get_current_activity 
        session_output = self.get_session_each(session_type, session_) 
    File "/opt/plexpy/plexpy/pmsconnect.py", line 1351, in get_session_each 
        metadata_details = self.get_metadata_details(rating_key=helpers.get_xml_attr(session, 'ratingKey')) 
    File "/opt/plexpy/plexpy/pmsconnect.py", line 782, in get_metadata_details 
        helpers.get_xml_attr(metadata_main, 'title')) 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
```

**Comment by halali** [comment]
i Have same issue
