### ISSUE TITLE
PlexPy Wont Start; IOError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by 1liminal1** [Tautulli/Tautulli#985]
C:\Program Files (x86)\PlexPy>plexpy.py
Unable to create the log directory. Logging to screen only.
Traceback (most recent call last):
  File "C:\Program Files (x86)\PlexPy\PlexPy.py", line 260, in <module>
    main()
  File "C:\Program Files (x86)\PlexPy\PlexPy.py", line 186, in main
    plexpy.initialize(config_file)
  File "C:\Program Files (x86)\PlexPy\plexpy\__init__.py", line 129, in initiali
ze
    verbose=VERBOSE)
  File "C:\Program Files (x86)\PlexPy\plexpy\logger.py", line 205, in initLogger

    file_handler = handlers.RotatingFileHandler(filename, maxBytes=MAX_SIZE, bac
kupCount=MAX_FILES)
  File "C:\Python27\lib\logging\handlers.py", line 118, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\handlers.py", line 65, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\__init__.py", line 893, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 912, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\PlexPy\\
None\\plexpy.log'

**Comment by JonnyWong16** [comment]
Delete the `log_dir = xxxxx` line in your config.ini file.

**Comment by 1liminal1** [comment]
That was the first thing I looked for, but a search turns up nothing. Anyway, im going to delete it all and use  the download instead of Git GUI.

Let you know how I go

**Comment by JonnyWong16** [comment]
Also, don't install in C:\Program Files. PlexPy doesn't have permissions to create folders there.

**Comment by 1liminal1** [comment]
Ahh ok, ill move it

Thanks, I think thats what it is, because I can see it the py file telling it to create a loging file.

**Comment by 1liminal1** [comment]
That was it thanks :)
